"use client";
import { useActionState } from "react";
import type { CatalogActionState } from "@/lib/catalog/actions";
export type CatalogField={name:string;label:string;type?:string;required?:boolean;options?:{value:string;label:string}[]};
type Value=string|number|boolean|null|undefined;
export function CatalogForm({action,fields,title,values={}}:{action:(state:CatalogActionState,form:FormData)=>Promise<CatalogActionState>;fields:CatalogField[];title:string;values?:Record<string,Value>}){
 const[state,formAction,pending]=useActionState(action,{});
 return <form action={formAction} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">{values.id?<input type="hidden" name="id" value={String(values.id)}/>:null}<h2 className="text-lg font-semibold">{title}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{fields.map(field=><label key={field.name} className="text-sm font-medium text-slate-700">{field.label}{field.options?<select name={field.name} required={field.required} defaultValue={String(values[field.name]??field.options[0]?.value??"")} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2">{field.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.type==="checkbox"?<input name={field.name} type="checkbox" defaultChecked={Boolean(values[field.name])} className="ml-3"/>:field.type==="textarea"?<textarea name={field.name} required={field.required} defaultValue={values[field.name]==null?"":String(values[field.name])} className="mt-1 min-h-24 w-full rounded-lg border border-slate-300 px-3 py-2"/>:<input name={field.name} type={field.type??"text"} required={field.required} defaultValue={values[field.name]==null?"":String(values[field.name])} step={field.type==="number"?"any":undefined} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"/>}</label>)}</div><div className="mt-4 flex items-center gap-3"><button disabled={pending} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending?"Saving…":"Save"}</button>{state.error?<p role="alert" className="text-sm text-red-700">{state.error}</p>:state.success?<p role="status" className="text-sm text-emerald-700">{state.success}</p>:null}</div></form>;
}
