"use server";
import {revalidatePath} from"next/cache";import{getAppContext}from"@/lib/auth/authorization";import{createClient}from"@/lib/supabase/server";export type InventoryActionState={error?:string;success?:string};
const uuid=(v:FormDataEntryValue|null,optional=false)=>{const s=String(v??"");if(optional&&!s)return null;if(!/^[0-9a-f-]{36}$/i.test(s))throw new Error("Invalid identifier.");return s},text=(v:FormDataEntryValue|null,max=500,required=false)=>{const s=String(v??"").trim();if(required&&!s||s.length>max)throw new Error("Invalid text value.");return s},num=(v:FormDataEntryValue|null,required=false)=>{const s=String(v??"").trim();if(!s&&!required)return null;const n=Number(s);if(!Number.isFinite(n))throw new Error("Invalid quantity.");return n},date=(v:FormDataEntryValue|null)=>text(v,10)||null;
async function context(permission:string){const c=await getAppContext();if(!c.membership?.permissions.includes(permission))throw new Error("Not authorized.");return c.membership.organizationId}async function rpc(permission:string,fn:string,args:Record<string,unknown>,paths:string[]){const org=await context(permission),s=await createClient(),{error}=await s.rpc(fn as never,{target_organization_id:org,...args}as never);if(error)return{error:error.code==="23505"?"That code, reference, or request key already exists.":"The operation could not be completed."};for(const path of paths)revalidatePath(path);revalidatePath("/administration/audit-log");return{success:"Operation completed."}}
export async function saveWarehouse(_:InventoryActionState,f:FormData){try{return await rpc("warehouses.manage","admin_save_warehouse",{target_id:uuid(f.get("id"),true),target_code:text(f.get("code"),40,true),target_name:text(f.get("name"),160,true),target_status:String(f.get("status")),target_city:text(f.get("city"),120),target_region:text(f.get("region"),120),target_postal:text(f.get("postal"),40),target_country:text(f.get("country"),80,true),target_timezone:text(f.get("timezone"),80,true),target_notes:text(f.get("notes"),5000)},["/warehouses"])}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
export async function saveLocation(_:InventoryActionState,f:FormData){try{return await rpc("warehouses.manage","admin_save_warehouse_location",{target_id:uuid(f.get("id"),true),target_warehouse_id:uuid(f.get("warehouseId")),target_code:text(f.get("code"),60,true),target_name:text(f.get("name"),160,true),target_type:text(f.get("type"),80,true),target_status:String(f.get("status")),target_description:text(f.get("description"),2000),target_notes:text(f.get("notes"),5000)},["/warehouses/locations"])}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
export async function saveLot(_:InventoryActionState,f:FormData){try{const c=await getAppContext(),canSupplier=c.membership?.permissions.includes("suppliers.view");return await rpc("inventory.manage_lots","admin_save_inventory_lot",{target_id:uuid(f.get("id"),true),target_variant_id:uuid(f.get("variantId")),target_lot_number:text(f.get("lotNumber"),120,true),target_manufacturer_lot:text(f.get("manufacturerLot"),120),target_manufactured:date(f.get("manufactured")),target_received:date(f.get("received")),target_expiration:date(f.get("expiration")),target_bud:date(f.get("bud")),target_uom:text(f.get("uom"),40,true),target_status:String(f.get("status")),target_notes:text(f.get("notes"),5000),target_supplier_id:canSupplier?uuid(f.get("supplierId"),true):null,target_supplier_relationship_id:null},["/inventory/lots"])}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
const requestKey=(f:FormData)=>text(f.get("requestKey"),120,true);
export async function receiveInventory(_:InventoryActionState,f:FormData){try{return await rpc("inventory.receive","admin_receive_inventory",{target_warehouse_id:uuid(f.get("warehouseId")),target_location_id:uuid(f.get("locationId")),target_lot_id:uuid(f.get("lotId")),target_quantity:num(f.get("quantity"),true),target_reference:text(f.get("reference"),120,true),target_expected:num(f.get("expected")),target_discrepancy_reason:text(f.get("reason"),1000),target_idempotency_key:requestKey(f)},["/receiving","/inventory"])}catch(e){return{error:e instanceof Error?e.message:"Unable to receive."}}}
export async function adjustInventory(_:InventoryActionState,f:FormData){try{return await rpc("inventory.adjust","admin_adjust_inventory",{target_warehouse_id:uuid(f.get("warehouseId")),target_location_id:uuid(f.get("locationId")),target_lot_id:uuid(f.get("lotId")),target_quantity_delta:num(f.get("quantity"),true),target_reason:text(f.get("reason"),1000,true),target_idempotency_key:requestKey(f)},["/inventory","/inventory/transactions"])}catch(e){return{error:e instanceof Error?e.message:"Unable to adjust."}}}
export async function transferInventory(_:InventoryActionState,f:FormData){try{return await rpc("inventory.transfer","admin_transfer_inventory",{target_source_warehouse_id:uuid(f.get("sourceWarehouseId")),target_source_location_id:uuid(f.get("sourceLocationId")),target_destination_warehouse_id:uuid(f.get("destinationWarehouseId")),target_destination_location_id:uuid(f.get("destinationLocationId")),target_lot_id:uuid(f.get("lotId")),target_quantity:num(f.get("quantity"),true),target_reason:text(f.get("reason"),1000,true),target_idempotency_key:requestKey(f)},["/inventory","/inventory/transactions"])}catch(e){return{error:e instanceof Error?e.message:"Unable to transfer."}}}
export async function quarantineInventory(_:InventoryActionState,f:FormData){try{return await rpc("inventory.quarantine","admin_set_inventory_quarantine",{target_warehouse_id:uuid(f.get("warehouseId")),target_location_id:uuid(f.get("locationId")),target_lot_id:uuid(f.get("lotId")),target_quantity:num(f.get("quantity"),true),should_quarantine:f.get("operation")==="quarantine",target_reason:text(f.get("reason"),1000,true),target_idempotency_key:requestKey(f)},["/inventory","/inventory/lots","/inventory/transactions"])}catch(e){return{error:e instanceof Error?e.message:"Unable to change quarantine."}}}
export async function markInventoryDamaged(_:InventoryActionState,f:FormData){try{return await rpc("inventory.adjust","admin_mark_inventory_damaged",{target_warehouse_id:uuid(f.get("warehouseId")),target_location_id:uuid(f.get("locationId")),target_lot_id:uuid(f.get("lotId")),target_quantity:num(f.get("quantity"),true),target_reason:text(f.get("reason"),1000,true),target_idempotency_key:requestKey(f)},["/inventory","/inventory/transactions"])}catch(e){return{error:e instanceof Error?e.message:"Unable to mark inventory damaged."}}}
