"use client";
import{useActionState}from"react";import{assignShipmentAllocation,cancelShipment,confirmPick,createPackage,createPickList,createShipment,dispatchShipment,lockShipment,setPackageContent,verifyShipment,type FulfillmentState}from"@/lib/fulfillment/actions";
const Key=()=> <input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/>;
function Result({state}:{state:FulfillmentState}){return state.error?<p role="alert" className="text-sm text-red-700">{state.error}</p>:state.success?<p role="status" className="text-sm text-emerald-700">{state.success}</p>:null}
export function CreatePickForm({orderId,warehouseId}:{orderId:string;warehouseId:string}){const[s,a,p]=useActionState(createPickList,{});return <form action={a} className="flex gap-2"><input type="hidden" name="orderId" value={orderId}/><input type="hidden" name="warehouseId" value={warehouseId}/><Key/><button disabled={p} className="rounded bg-slate-900 px-3 py-2 text-sm text-white">Create pick list</button><Result state={s}/></form>}
export function ConfirmPickForm({pickListId,pickLineId,quantity}:{pickListId:string;pickLineId:string;quantity:number}){const[s,a,p]=useActionState(confirmPick,{});return <form action={a} className="flex items-center gap-2"><input type="hidden" name="pickListId" value={pickListId}/><input type="hidden" name="pickLineId" value={pickLineId}/><input aria-label="Picked quantity" name="quantity" type="number" min="0" step="any" defaultValue={quantity} className="w-24 rounded border p-1"/><Key/><button disabled={p} className="rounded border px-3 py-1 text-sm">Confirm pick</button><Result state={s}/></form>}
export function CreateShipmentForm({orderId}:{orderId:string}){const[s,a,p]=useActionState(createShipment,{});return <form action={a}><input type="hidden" name="orderId" value={orderId}/><Key/><button disabled={p} className="rounded bg-slate-900 px-3 py-2 text-sm text-white">Plan split shipment</button><Result state={s}/></form>}
export function AssignAllocationForm({shipmentId,allocationId}:{shipmentId:string;allocationId:string}){const[s,a,p]=useActionState(assignShipmentAllocation,{});return <form action={a}><input type="hidden" name="shipmentId" value={shipmentId}/><input type="hidden" name="allocationId" value={allocationId}/><Key/><button disabled={p} className="rounded border px-3 py-1 text-sm">Assign reservation</button><Result state={s}/></form>}
export function PackageForm({shipmentId}:{shipmentId:string}){const[s,a,p]=useActionState(createPackage,{});return <form action={a} className="flex flex-wrap gap-2"><input type="hidden" name="shipmentId" value={shipmentId}/><input aria-label="Package weight" name="weight" type="number" min="0.001" step="any" placeholder="Weight" required className="w-28 rounded border p-2"/><input name="weightUnit" defaultValue="lb" maxLength={8} className="w-20 rounded border p-2"/><Key/><button disabled={p} className="rounded border px-3 py-2 text-sm">Create package</button><Result state={s}/></form>}
export function PackageContentForm({packageId,shipmentLineId,quantity}:{packageId:string;shipmentLineId:string;quantity:number}){const[s,a,p]=useActionState(setPackageContent,{});return <form action={a} className="flex gap-2"><input type="hidden" name="packageId" value={packageId}/><input type="hidden" name="shipmentLineId" value={shipmentLineId}/><input aria-label="Package content quantity" name="quantity" type="number" min="0.001" step="any" defaultValue={quantity} className="w-24 rounded border p-1"/><Key/><button disabled={p} className="rounded border px-3 py-1 text-sm">Save contents</button><Result state={s}/></form>}
export function VerificationForm({shipmentId,expected}:{shipmentId:string;expected:number}){const[s,a,p]=useActionState(verifyShipment,{});return <form action={a} className="space-y-2"><input type="hidden" name="shipmentId" value={shipmentId}/><label className="mr-2">Result<select name="status" className="ml-2 rounded border p-1"><option value="passed">Passed</option><option value="hold">Hold</option><option value="failed">Failed</option></select></label><label>Verified quantity<input name="verifiedQuantity" aria-label="Verified quantity" type="number" min="0" step="any" defaultValue={expected} className="ml-2 w-24 rounded border p-1"/></label><input name="notes" maxLength={500} placeholder="Notes" className="ml-2 rounded border p-1"/><Key/><button disabled={p} className="ml-2 rounded bg-emerald-700 px-3 py-1 text-sm text-white">Record verification</button><Result state={s}/></form>}
export function ShipmentStateForms({shipmentId,status}:{shipmentId:string;status:string}){const[l,lock,locking]=useActionState(lockShipment,{}),[d,dispatch,dispatching]=useActionState(dispatchShipment,{}),[c,cancel,cancelling]=useActionState(cancelShipment,{});return <div className="flex flex-wrap gap-2">{status==='warehouse_verified'?<form action={lock}><input type="hidden" name="shipmentId" value={shipmentId}/><Key/><button disabled={locking} className="rounded bg-blue-700 px-3 py-1 text-sm text-white">Lock ready-to-ship</button><Result state={l}/></form>:null}{status==='ready_to_ship'?<form action={dispatch}><input type="hidden" name="shipmentId" value={shipmentId}/><Key/><button disabled={dispatching} className="rounded bg-indigo-700 px-3 py-1 text-sm text-white">Dispatch and fulfill</button><Result state={d}/></form>:null}{!['ready_to_ship','dispatched','cancelled'].includes(status)?<form action={cancel}><input type="hidden" name="shipmentId" value={shipmentId}/><Key/><button disabled={cancelling} className="rounded bg-red-700 px-3 py-1 text-sm text-white">Cancel planned shipment</button><Result state={c}/></form>:null}</div>}
