export type NavigationItem = { label: string; href: string; permission?: string };

export const primaryNavigation: NavigationItem[] = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Exceptions & Returns", href: "/exceptions", permission: "cases.view" },
  { label: "Billing", href: "/billing", permission: "billing.view" },
  { label: "Client Catalog Admin", href: "/client-catalog-admin", permission: "client_catalog.manage" },
  { label: "Your Catalog", href: "/client-catalog", permission: "client_catalog.view" },
  { label: "Orders", href: "/orders", permission: "orders.view" },
  { label: "Order Allocation", href: "/orders/allocations", permission: "order_allocation.view" },
  { label: "Fulfillment", href: "/fulfillment", permission: "fulfillment.shipments.view" },
  { label: "Inventory", href: "/inventory", permission: "inventory.view" },
  { label: "Warehouses", href: "/warehouses", permission: "warehouses.view" },
  { label: "Products", href: "/products", permission: "products.view" },
  { label: "Suppliers", href: "/suppliers", permission: "suppliers.view" },
  { label: "Purchasing", href: "/purchasing", permission: "purchasing.view" },
  { label: "Inbound", href: "/inbound-shipments", permission: "receiving.view" },
  { label: "Clients", href: "/clients", permission: "clients.read" },
  { label: "Client Roles", href: "/client-relationships", permission: "client_capabilities.view" },
  { label: "Salespeople", href: "/salespeople", permission: "salespeople.view" },
  { label: "Pricing Tiers", href: "/pricing-tiers", permission: "pricing_tiers.view" },
  { label: "Customers", href: "/customers", permission: "customers.view" },
  { label: "Shipping", href: "/shipping", permission: "shipping.read" },
  { label: "Receiving", href: "/receiving", permission: "receiving.view" },
  { label: "Work Queues", href: "/operations", permission: "receiving.view" },
  { label: "QC", href: "/qc", permission: "qc.view" },
  { label: "Quarantine", href: "/qc/quarantine", permission: "qc.view" },
  { label: "Quality Documents", href: "/quality-documents", permission: "quality_documents.view" },
  { label: "Supplier Issues", href: "/supplier-issues", permission: "supplier_issues.view" },
  { label: "Branding", href: "/branding", permission: "branding.read" },
  { label: "Messages", href: "/messages", permission: "messages.read" },
  { label: "Reports", href: "/reports", permission: "salesperson.dashboard" },
  { label: "Knowledge Library", href: "/library", permission: "library.view" },
  { label: "Administration", href: "/administration", permission: "administration.access" },
];

export const administrationNavigation: NavigationItem[] = [
  { label: "Users", href: "/administration/users", permission: "memberships.read" },
  { label: "Memberships", href: "/administration/memberships", permission: "memberships.read" },
  { label: "Invitations", href: "/administration/invitations", permission: "memberships.manage" },
  { label: "Roles", href: "/administration/roles", permission: "roles.read" },
  { label: "Permissions", href: "/administration/permissions", permission: "roles.read" },
  { label: "Audit Log", href: "/administration/audit-log", permission: "audit.read" },
];
