"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export type OrderState={error?:string;success?:string;orderId?:string};
const value=(f:FormData,key:string,max=200)=>{const v=String(f.get(key)??"").trim();if(v.length>max||/[\u0000-\u001f]/.test(v))throw Error(`Invalid ${key}.`);return v;};
const uuid=(f:FormData,key:string)=>{const v=value(f,key,36);if(!/^[\da-f]{8}(-[\da-f]{4}){3}-[\da-f]{12}$/i.test(v))throw Error(`Invalid ${key}.`);return v;};
export async function submitOrder(_:OrderState,f:FormData):Promise<OrderState>{
 await requireUser();try{const currency=value(f,"currency",3).toUpperCase(),key=value(f,"idempotencyKey",120);if(!/^[A-Z]{3}$/.test(currency)||key.length<8)throw Error("Invalid currency or request key.");
  const raw=JSON.parse(value(f,"lines",20000)) as unknown;if(!Array.isArray(raw)||raw.length<1||raw.length>100)throw Error("Select at least one order line.");
  const lines=raw.map((x)=>{if(!x||typeof x!=="object")throw Error("Invalid order line.");const r=x as Record<string,unknown>,entry_id=String(r.entry_id??""),quantity=Number(r.quantity);if(!/^[\da-f]{8}(-[\da-f]{4}){3}-[\da-f]{12}$/i.test(entry_id)||!Number.isSafeInteger(quantity)||quantity<1||quantity>1000000)throw Error("Invalid order line.");return{entry_id,quantity};});
  if(new Set(lines.map(x=>x.entry_id)).size!==lines.length)throw Error("Duplicate catalog items are not allowed.");
  const s=await createClient(),{data,error}=await s.rpc("submit_order",{target_client_organization_id:uuid(f,"clientId"),target_customer_id:uuid(f,"customerId"),target_address_id:uuid(f,"addressId"),target_currency:currency,target_lines:lines,target_idempotency_key:key});
  if(error)return{error:"Order was not submitted. Check access, customer/address, catalog availability, quantity, and current pricing."};
  revalidatePath("/orders");revalidatePath(`/orders/${data}`);revalidatePath("/administration/audit-log");return{success:"Order submitted and verification created.",orderId:data};
 }catch(e){return{error:e instanceof Error?e.message:"Unable to submit order."};}
}
export async function transitionOrder(_:OrderState,f:FormData):Promise<OrderState>{await requireUser();try{const target=value(f,"status");if(target!=="accepted"&&target!=="cancelled")throw Error("Invalid Phase 4A status.");const id=uuid(f,"orderId"),s=await createClient(),{error}=await s.rpc("transition_order_status",{target_order_id:id,target_status:target});if(error)return{error:"Transition is not permitted."};revalidatePath("/orders");revalidatePath(`/orders/${id}`);return{success:`Order ${target}.`,orderId:id};}catch(e){return{error:e instanceof Error?e.message:"Unable to update order."};}}
export async function saveOrderServiceAccess(_:OrderState,f:FormData):Promise<OrderState>{await requireUser();try{const access=value(f,"access"),version=Number(value(f,"version",12));if(!['none','read','manage'].includes(access)||!Number.isSafeInteger(version)||version<1)throw Error("Invalid service access.");const s=await createClient(),{error}=await s.rpc('admin_save_order_service_access',{target_service_id:uuid(f,'serviceId'),target_access:access,target_expected_version:version});if(error)return{error:'Only an active super-admin may change a current service relationship.'};revalidatePath('/orders/service-access');return{success:'Order service access saved and audited.'};}catch(e){return{error:e instanceof Error?e.message:'Unable to save access.'};}}
export async function allocateOrder(_:OrderState,f:FormData):Promise<OrderState>{await requireUser();try{const kind=value(f,"demandType"),eta=value(f,"expectedAt",40),reason=value(f,"reason",500),key=value(f,"idempotencyKey",120),id=uuid(f,"orderId");if(!['backorder','preorder'].includes(kind)||key.length<8)throw Error("Invalid allocation request.");const s=await createClient(),{error}=await s.rpc('admin_allocate_order',{target_order_id:id,target_warehouse_id:uuid(f,'warehouseId'),target_demand_type:kind,target_expected_available_at:(eta||null)as string,target_reason:reason,target_idempotency_key:key});if(error)return{error:'Allocation was denied or inventory relationships are invalid.'};revalidatePath('/orders');revalidatePath('/orders/allocations');revalidatePath(`/orders/${id}`);return{success:'Eligible inventory reserved and remaining demand recorded.',orderId:id};}catch(e){return{error:e instanceof Error?e.message:'Unable to allocate order.'};}}
export async function cancelOrderAllocations(_:OrderState,f:FormData):Promise<OrderState>{await requireUser();try{const id=uuid(f,'orderId'),key=value(f,'idempotencyKey',120);if(key.length<8)throw Error('Invalid cancellation request.');const s=await createClient(),{error}=await s.rpc('admin_cancel_order_allocations',{target_order_id:id,target_idempotency_key:key});if(error)return{error:'Cancellation was denied.'};revalidatePath('/orders');revalidatePath('/orders/allocations');revalidatePath(`/orders/${id}`);return{success:'Order cancelled and active reservations released.',orderId:id};}catch(e){return{error:e instanceof Error?e.message:'Unable to cancel allocations.'};}}
export async function processOrderDemands(_:OrderState,f:FormData):Promise<OrderState>{await requireUser();try{const s=await createClient(),{data,error}=await s.rpc('admin_process_order_demands',{target_organization_id:uuid(f,'organizationId'),target_variant_id:uuid(f,'variantId'),target_idempotency_key:value(f,'idempotencyKey',120)});if(error)return{error:'Demand processing was denied.'};revalidatePath('/orders');revalidatePath('/orders/allocations');return{success:`Processed ${data??0} demand record(s).`};}catch(e){return{error:e instanceof Error?e.message:'Unable to process demand.'};}}
export async function submitOrderAddendum(_:OrderState,f:FormData):Promise<OrderState>{await requireUser();try{const raw=JSON.parse(value(f,'lines',20000)) as unknown;if(!Array.isArray(raw)||raw.length<1||raw.length>100)throw Error('Add at least one catalog entry.');const lines=raw.map(x=>{if(!x||typeof x!=='object')throw Error('Invalid addendum line.');const r=x as Record<string,unknown>,entry_id=String(r.entry_id??''),quantity=Number(r.quantity);if(!/^[\da-f]{8}(-[\da-f]{4}){3}-[\da-f]{12}$/i.test(entry_id)||!Number.isSafeInteger(quantity)||quantity<1||quantity>1000000)throw Error('Invalid addendum line.');return{entry_id,quantity};});const id=uuid(f,'orderId'),key=value(f,'idempotencyKey',120);if(key.length<8)throw Error('Invalid request key.');const s=await createClient(),{error}=await s.rpc('submit_order_addendum',{target_client_organization_id:uuid(f,'clientId'),target_order_id:id,target_lines:lines,target_reason:value(f,'reason',1000),target_idempotency_key:key});if(error)return{error:'Addendum was denied or current catalog pricing is unavailable.'};revalidatePath('/orders');revalidatePath(`/orders/${id}`);revalidatePath('/administration/audit-log');return{success:'Addendum applied and audited.',orderId:id};}catch(e){return{error:e instanceof Error?e.message:'Unable to apply addendum.'};}}
