"use server";

import { revalidatePath } from "next/cache";
import { getAppContext } from "@/lib/auth/authorization";
import { createClient } from "@/lib/supabase/server";

export type CatalogActionState = { error?: string; success?: string };
const uuid = (v: FormDataEntryValue | null, optional = false) => { const s=String(v??""); if(optional&&!s)return null; if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)) throw new Error("Invalid identifier."); return s; };
const text = (v: FormDataEntryValue|null, max:number, required=false) => { const s=String(v??"").trim(); if((required&&!s)||s.length>max) throw new Error("Invalid text value."); return s; };
const number = (v: FormDataEntryValue|null, min=0) => { const s=String(v??"").trim(); if(!s)return null; const n=Number(s); if(!Number.isFinite(n)||n<min)throw new Error("Invalid numeric value."); return n; };
async function org(permission:string){const c=await getAppContext();if(!c.membership||!c.membership.permissions.includes(permission))throw new Error("Not authorized.");return c.membership.organizationId;}
async function call(fn:string,args:Record<string,unknown>,path:string){const s=await createClient();const {error}=await s.rpc(fn as never,args as never);if(error)return {error:error.code==="23505"?"That code or SKU already exists in this organization.":"The change could not be saved."};revalidatePath(path);revalidatePath("/administration/audit-log");return {success:"Saved successfully."};}

export async function saveCategory(_:CatalogActionState,f:FormData):Promise<CatalogActionState>{try{const o=await org("categories.manage");return await call("admin_save_product_category",{target_id:uuid(f.get("id"),true),target_organization_id:o,target_name:text(f.get("name"),120,true),target_slug:text(f.get("slug"),120,true),target_description:text(f.get("description"),2000),target_status:String(f.get("status")),target_display_order:number(f.get("displayOrder"),0)??0},"/products/categories");}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
export async function saveProduct(_:CatalogActionState,f:FormData):Promise<CatalogActionState>{try{const o=await org("products.manage");return await call("admin_save_product",{target_id:uuid(f.get("id"),true),target_organization_id:o,target_category_id:uuid(f.get("categoryId")),target_name:text(f.get("name"),200,true),target_description:text(f.get("description"),10000),target_type:text(f.get("type"),80,true),target_status:String(f.get("status")),target_uom:text(f.get("uom"),40,true),target_lot:f.get("lot")==="on",target_expiration:f.get("expiration")==="on",target_coa:f.get("coa")==="on",target_backorder:f.get("backorder")==="on",target_notes:text(f.get("notes"),10000)},"/products");}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
export async function saveVariant(_:CatalogActionState,f:FormData):Promise<CatalogActionState>{try{const o=await org("products.manage");return await call("admin_save_product_variant",{target_id:uuid(f.get("id"),true),target_organization_id:o,target_product_id:uuid(f.get("productId")),target_sku:text(f.get("sku"),100,true),target_name:text(f.get("name"),200,true),target_strength:number(f.get("strength")),target_strength_unit:text(f.get("strengthUnit"),40),target_package_size:number(f.get("packageSize"),0.000001),target_package_unit:text(f.get("packageUnit"),40),target_concentration:text(f.get("concentration"),100),target_volume:number(f.get("volume")),target_volume_unit:text(f.get("volumeUnit"),40),target_barcode:text(f.get("barcode"),100),target_status:String(f.get("status"))},"/products/variants");}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
export async function saveSupplier(_:CatalogActionState,f:FormData):Promise<CatalogActionState>{try{const o=await org("suppliers.manage");return await call("admin_save_supplier",{target_id:uuid(f.get("id"),true),target_organization_id:o,target_name:text(f.get("name"),200,true),target_code:text(f.get("code"),60,true),target_contact:text(f.get("contact"),200),target_email:text(f.get("email"),320),target_phone:text(f.get("phone"),60),target_website:text(f.get("website"),500),target_country:text(f.get("country"),100),target_address1:text(f.get("address1"),300),target_address2:text(f.get("address2"),300),target_city:text(f.get("city"),120),target_region:text(f.get("region"),120),target_postal:text(f.get("postal"),40),target_status:String(f.get("status")),target_lead:number(f.get("lead")),target_notes:text(f.get("notes"),10000)},"/suppliers");}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
export async function saveSupplierProduct(_:CatalogActionState,f:FormData):Promise<CatalogActionState>{try{const o=await org("suppliers.manage");const c=await getAppContext();const canCost=c.membership?.permissions.includes("supplier_costs.manage");return await call("admin_save_supplier_product",{target_id:uuid(f.get("id"),true),target_organization_id:o,target_supplier_id:uuid(f.get("supplierId")),target_variant_id:uuid(f.get("variantId")),target_supplier_sku:text(f.get("supplierSku"),100),target_lead:number(f.get("lead")),target_moq:number(f.get("moq"),0.000001),target_preferred:f.get("preferred")==="on",target_status:String(f.get("status")),target_cost:canCost?number(f.get("cost")):null,target_currency:canCost?text(f.get("currency"),3,true).toUpperCase():"USD"},"/suppliers/products");}catch(e){return{error:e instanceof Error?e.message:"Unable to save."}}}
