"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export type FulfillmentState={error?:string;success?:string;id?:string};
const text=(f:FormData,k:string,max=300)=>{const v=String(f.get(k)??"").trim();if(v.length>max||/[\u0000-\u001f]/.test(v))throw Error(`Invalid ${k}.`);return v};
const id=(f:FormData,k:string)=>{const v=text(f,k,36);if(!/^[\da-f]{8}(-[\da-f]{4}){3}-[\da-f]{12}$/i.test(v))throw Error(`Invalid ${k}.`);return v};
const key=(f:FormData)=>{const v=text(f,"idempotencyKey",120);if(v.length<8)throw Error("Invalid request key.");return v};
async function call(name:string,args:Record<string,unknown>,success:string,path?:string):Promise<FulfillmentState>{await requireUser();try{const s=await createClient();const rpc=s.rpc as unknown as (fn:string,params:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>;const{data,error}=await rpc(name,args);if(error)return{error:"Operation denied or the fulfillment state is no longer eligible."};if(path)revalidatePath(path);revalidatePath("/fulfillment");return{success,id:typeof data==="string"?data:undefined};}catch(e){return{error:e instanceof Error?e.message:"Fulfillment operation failed."};}}
export async function createPickList(_:FulfillmentState,f:FormData){return call("admin_create_pick_list",{target_order_id:id(f,"orderId"),target_warehouse_id:id(f,"warehouseId"),target_idempotency_key:key(f)},"Pick list created.");}
export async function confirmPick(_:FulfillmentState,f:FormData){const q=Number(text(f,"quantity",40));if(!Number.isFinite(q)||q<0) return{error:"Invalid pick quantity."};return call("admin_confirm_pick_line",{target_pick_list_id:id(f,"pickListId"),target_pick_line_id:id(f,"pickLineId"),target_quantity:q,target_idempotency_key:key(f)},"Pick confirmed.");}
export async function createShipment(_:FulfillmentState,f:FormData){return call("admin_create_shipment",{target_order_id:id(f,"orderId"),target_idempotency_key:key(f)},"Shipment planned.");}
export async function assignShipmentAllocation(_:FulfillmentState,f:FormData){return call("admin_assign_shipment_allocation",{target_shipment_id:id(f,"shipmentId"),target_allocation_id:id(f,"allocationId"),target_idempotency_key:key(f)},"Reservation chunk assigned to shipment.");}
export async function createPackage(_:FulfillmentState,f:FormData){const w=Number(text(f,"weight",40));if(!Number.isFinite(w)||w<=0)return{error:"Package weight must be positive."};return call("admin_create_shipment_package",{target_shipment_id:id(f,"shipmentId"),target_weight:w,target_weight_unit:text(f,"weightUnit",8)||"lb",target_idempotency_key:key(f)},"Package created.");}
export async function setPackageContent(_:FulfillmentState,f:FormData){const q=Number(text(f,"quantity",40));if(!Number.isFinite(q)||q<=0)return{error:"Package quantity must be positive."};return call("admin_set_package_content",{target_package_id:id(f,"packageId"),target_shipment_line_id:id(f,"shipmentLineId"),target_quantity:q,target_idempotency_key:key(f)},"Package content saved.");}
export async function verifyShipment(_:FulfillmentState,f:FormData){const q=Number(text(f,"verifiedQuantity",40)),status=text(f,"status",20);if(!Number.isFinite(q)||q<0||!['passed','failed','hold'].includes(status))return{error:"Invalid warehouse verification."};return call("admin_verify_shipment",{target_shipment_id:id(f,"shipmentId"),target_status:status,target_verified_quantity:q,target_notes:text(f,"notes",500),target_idempotency_key:key(f)},"Warehouse verification recorded.");}
export async function lockShipment(_:FulfillmentState,f:FormData){return call("admin_lock_shipment",{target_shipment_id:id(f,"shipmentId"),target_idempotency_key:key(f)},"Shipment locked and ready to ship.");}
export async function dispatchShipment(_:FulfillmentState,f:FormData){return call("admin_dispatch_shipment",{target_shipment_id:id(f,"shipmentId"),target_idempotency_key:key(f)},"Shipment dispatched; inventory fulfilled exactly once.");}
export async function cancelShipment(_:FulfillmentState,f:FormData){return call("admin_cancel_planned_shipment",{target_shipment_id:id(f,"shipmentId"),target_idempotency_key:key(f)},"Planned shipment cancelled and reservations released.");}
