begin;

create type public.purchase_order_status as enum ('draft','submitted','confirmed','partially_received','received','delayed','cancelled','closed');
create type public.purchase_order_line_status as enum ('open','partially_received','received','cancelled','closed');
create type public.inbound_shipment_status as enum ('expected','in_transit','delayed','delivered','receiving','partially_received','received','exception','closed');
create type public.qc_status as enum ('pending','passed','partial_pass','failed','quarantined','released','rejected');
create type public.quality_document_status as enum ('pending','approved','rejected','superseded');
create type public.supplier_issue_status as enum ('open','supplier_contacted','awaiting_response','replacement_pending','credit_pending','resolved','closed');
create type public.supplier_issue_severity as enum ('low','medium','high','critical');
create type public.supplier_resolution_type as enum ('replacement_product','supplier_credit','refund','reshipment','no_action','other');

insert into public.permissions(code,name,description) values
('purchasing.view','View purchasing','View purchase orders and inbound procurement records'),
('purchasing.manage','Manage purchasing','Create and administer purchase orders and inbound shipments'),
('purchasing.view_costs','View purchasing costs','View acquisition and freight costs'),
('receiving.view','View receiving','View procurement receiving records'),
('receiving.manage','Manage receiving','Complete controlled procurement receipts'),
('qc.view','View quality control','View internal QC inspections and work queues'),
('qc.inspect','Perform QC inspections','Record quality inspection decisions'),
('qc.release','Release QC inventory','Release approved QC-held inventory'),
('supplier_issues.view','View supplier issues','View internal supplier discrepancies'),
('supplier_issues.manage','Manage supplier issues','Create and resolve supplier discrepancies'),
('quality_documents.view','View quality documents','View secure lot quality-document metadata'),
('quality_documents.manage','Manage quality documents','Create and update lot quality-document metadata')
on conflict(code) do nothing;

insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p
where r.code='SUPER_ADMIN' and p.code in ('purchasing.view','purchasing.manage','purchasing.view_costs','receiving.view','receiving.manage','qc.view','qc.inspect','qc.release','supplier_issues.view','supplier_issues.manage','quality_documents.view','quality_documents.manage') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('purchasing.view','purchasing.manage','purchasing.view_costs','receiving.view','receiving.manage','qc.view','qc.inspect','qc.release','supplier_issues.view','supplier_issues.manage','quality_documents.view','quality_documents.manage') where r.code='ADMIN' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('receiving.view','receiving.manage','qc.view','qc.inspect','quality_documents.view') where r.code='WAREHOUSE' on conflict do nothing;

create table public.purchase_orders(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict,
 supplier_id uuid not null, purchase_order_number text not null check(char_length(trim(purchase_order_number)) between 1 and 80), supplier_reference text,
 order_date date not null default current_date, expected_ship_date date, expected_delivery_date date, currency text not null default 'USD' check(currency~'^[A-Z]{3}$'),
 subtotal numeric(20,6) not null default 0 check(subtotal>=0), freight_cost numeric(20,6) not null default 0 check(freight_cost>=0), additional_cost numeric(20,6) not null default 0 check(additional_cost>=0),
 status public.purchase_order_status not null default 'draft', internal_notes text, created_by uuid not null references auth.users(id) on delete restrict,
 idempotency_key text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,
 unique(organization_id,purchase_order_number), unique(organization_id,id), unique(organization_id,idempotency_key)
);
create table public.purchase_order_lines(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null, purchase_order_id uuid not null, supplier_product_variant_id uuid not null,
 product_variant_id uuid not null, supplier_sku text, quantity_ordered numeric(20,6) not null check(quantity_ordered>0), quantity_received numeric(20,6) not null default 0 check(quantity_received>=0),
 unit_cost numeric(20,6) not null check(unit_cost>=0), currency text not null check(currency~'^[A-Z]{3}$'), expected_lot text, expected_expiration date, expected_bud date, expected_delivery_date date,
 status public.purchase_order_line_status not null default 'open', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id) on delete cascade,
 foreign key(organization_id,supplier_product_variant_id) references public.supplier_product_variants(organization_id,id) on delete restrict,
 foreign key(organization_id,product_variant_id) references public.product_variants(organization_id,id) on delete restrict,
 unique(organization_id,id)
);
create table public.inbound_shipments(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null, supplier_id uuid not null, purchase_order_id uuid,
 shipment_reference text not null, carrier text, tracking_number text, expected_arrival_date date, actual_arrival_at timestamptz,
 status public.inbound_shipment_status not null default 'expected', package_count integer check(package_count is null or package_count>=0), warehouse_id uuid not null, notes text,
 created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id), foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id),
 foreign key(organization_id,warehouse_id) references public.warehouses(organization_id,id), unique(organization_id,shipment_reference), unique(organization_id,id)
);

alter table public.receivings add column purchase_order_id uuid, add column inbound_shipment_id uuid;
alter table public.receivings add foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id), add foreign key(organization_id,inbound_shipment_id) references public.inbound_shipments(organization_id,id);
alter table public.receiving_lines add column purchase_order_line_id uuid, add column quantity_accepted numeric(20,6) not null default 0 check(quantity_accepted>=0), add column quantity_damaged numeric(20,6) not null default 0 check(quantity_damaged>=0), add column quantity_rejected numeric(20,6) not null default 0 check(quantity_rejected>=0), add column qc_required boolean not null default true;
alter table public.receiving_lines add foreign key(organization_id,purchase_order_line_id) references public.purchase_order_lines(organization_id,id), add check(quantity_accepted+quantity_damaged+quantity_rejected<=quantity_received);
alter table public.receiving_lines add unique(organization_id,id);

create table public.qc_inspections(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null, receiving_id uuid, receiving_line_id uuid, lot_id uuid not null, inbound_shipment_id uuid,
 inspector_user_id uuid not null references auth.users(id) on delete restrict, inspected_at timestamptz not null default now(), status public.qc_status not null,
 quantity_inspected numeric(20,6) not null check(quantity_inspected>0), quantity_approved numeric(20,6) not null default 0 check(quantity_approved>=0), quantity_quarantined numeric(20,6) not null default 0 check(quantity_quarantined>=0), quantity_rejected numeric(20,6) not null default 0 check(quantity_rejected>=0),
 reason_code text, notes text, idempotency_key text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(organization_id,receiving_id) references public.receivings(organization_id,id), foreign key(organization_id,receiving_line_id) references public.receiving_lines(organization_id,id),
 foreign key(organization_id,lot_id) references public.inventory_lots(organization_id,id), foreign key(organization_id,inbound_shipment_id) references public.inbound_shipments(organization_id,id),
 check(quantity_approved+quantity_quarantined+quantity_rejected=quantity_inspected), unique(organization_id,idempotency_key), unique(organization_id,id)
);
create table public.quality_documents(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null, lot_id uuid not null, document_type text not null check(document_type in('coa','sterility_report','endotoxin_report','supplier_certificate','receiving_document','qc_attachment','other')),
 document_name text not null, testing_laboratory text, report_reference text, test_date date, recorded_date date not null default current_date, status public.quality_document_status not null default 'pending', notes text,
 storage_reference text, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(organization_id,lot_id) references public.inventory_lots(organization_id,id), unique(organization_id,id)
);
create table public.supplier_issues(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null, supplier_id uuid not null, purchase_order_id uuid, receiving_id uuid, inbound_shipment_id uuid, lot_id uuid,
 issue_type text not null check(issue_type in('shortage','overage','wrong_product','wrong_variant','damaged_product','failed_qc','missing_documentation','incorrect_lot','expiration_bud','shipping_damage','delayed_shipment','other')),
 quantity_affected numeric(20,6) check(quantity_affected is null or quantity_affected>=0), severity public.supplier_issue_severity not null default 'medium', description text not null,
 status public.supplier_issue_status not null default 'open', supplier_notified_at timestamptz, internal_owner_user_id uuid references auth.users(id), resolution text,
 resolution_type public.supplier_resolution_type, replacement_quantity numeric(20,6) check(replacement_quantity is null or replacement_quantity>=0), replacement_expected_date date,
 credit_amount numeric(20,6) check(credit_amount is null or credit_amount>=0), currency text check(currency is null or currency~'^[A-Z]{3}$'), resolved_at timestamptz,
 created_by uuid not null references auth.users(id) on delete restrict, idempotency_key text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id), foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id),
 foreign key(organization_id,receiving_id) references public.receivings(organization_id,id), foreign key(organization_id,inbound_shipment_id) references public.inbound_shipments(organization_id,id), foreign key(organization_id,lot_id) references public.inventory_lots(organization_id,id),
 unique(organization_id,idempotency_key), unique(organization_id,id)
);

create index po_org_status_idx on public.purchase_orders(organization_id,status,expected_delivery_date);
create index po_lines_po_idx on public.purchase_order_lines(organization_id,purchase_order_id);
create index inbound_queue_idx on public.inbound_shipments(organization_id,status,expected_arrival_date);
create index qc_queue_idx on public.qc_inspections(organization_id,status,inspected_at);
create index quality_lot_idx on public.quality_documents(organization_id,lot_id);
create index supplier_issue_queue_idx on public.supplier_issues(organization_id,status,created_at);
create index lots_fefo_idx on public.inventory_lots(organization_id,status,expiration_date,bud_date);

alter table public.purchase_orders enable row level security; alter table public.purchase_order_lines enable row level security; alter table public.inbound_shipments enable row level security; alter table public.qc_inspections enable row level security; alter table public.quality_documents enable row level security; alter table public.supplier_issues enable row level security;
create policy po_read on public.purchase_orders for select to authenticated using(private.has_permission(organization_id,'purchasing.view'));
create policy po_lines_read on public.purchase_order_lines for select to authenticated using(private.has_permission(organization_id,'purchasing.view'));
create policy inbound_read on public.inbound_shipments for select to authenticated using(private.has_permission(organization_id,'purchasing.view') or private.has_permission(organization_id,'receiving.view'));
create policy qc_read on public.qc_inspections for select to authenticated using(private.has_permission(organization_id,'qc.view'));
create policy quality_document_read on public.quality_documents for select to authenticated using(private.has_permission(organization_id,'quality_documents.view'));
create policy supplier_issue_read on public.supplier_issues for select to authenticated using(private.has_permission(organization_id,'supplier_issues.view'));

grant select(id,organization_id,supplier_id,purchase_order_number,supplier_reference,order_date,expected_ship_date,expected_delivery_date,status,internal_notes,created_by,idempotency_key,created_at,updated_at) on public.purchase_orders to authenticated;
grant select(id,organization_id,purchase_order_id,supplier_product_variant_id,product_variant_id,supplier_sku,quantity_ordered,quantity_received,expected_lot,expected_expiration,expected_bud,expected_delivery_date,status,notes,created_at,updated_at) on public.purchase_order_lines to authenticated;
grant select on public.inbound_shipments,public.qc_inspections,public.quality_documents to authenticated;
grant select(id,organization_id,supplier_id,purchase_order_id,receiving_id,inbound_shipment_id,lot_id,issue_type,quantity_affected,severity,description,status,supplier_notified_at,internal_owner_user_id,resolution,resolution_type,replacement_quantity,replacement_expected_date,resolved_at,created_by,idempotency_key,created_at,updated_at) on public.supplier_issues to authenticated;
grant select,insert,update,delete on public.purchase_orders,public.purchase_order_lines,public.inbound_shipments,public.qc_inspections,public.quality_documents,public.supplier_issues to service_role;

create view public.procurement_work_queue with(security_invoker=true) as
select 'inbound'::text queue_type,id,organization_id,status::text,expected_arrival_date due_date,shipment_reference label from public.inbound_shipments where status in('expected','in_transit','delayed','delivered','receiving','partially_received')
union all select 'qc',id,organization_id,status::text,inspected_at::date,'QC '||id::text from public.qc_inspections where status in('pending','quarantined','partial_pass')
union all select 'supplier_issue',id,organization_id,status::text,null::date,issue_type from public.supplier_issues where status not in('resolved','closed');
create view public.lot_eligibility_queue with(security_invoker=true) as select id,organization_id,product_variant_id,lot_number,status,expiration_date,bud_date,least(expiration_date,bud_date) eligibility_date from public.inventory_lots where status in('pending_qc','quarantined','available') order by least(expiration_date,bud_date) nulls last;
grant select on public.procurement_work_queue,public.lot_eligibility_queue to authenticated;

create function private.require_phase3c_org(org_id uuid,permission_code text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=auth.uid();begin perform private.require_inventory_org(org_id,permission_code,actor);return actor;end$$;
revoke all on function private.require_phase3c_org(uuid,text) from public,anon,authenticated;

create function public.get_purchase_order_costs(target_organization_id uuid) returns table(id uuid,currency text,subtotal numeric,freight_cost numeric,additional_cost numeric) language plpgsql security definer set search_path='' as $$begin perform private.require_phase3c_org(target_organization_id,'purchasing.view_costs');return query select p.id,p.currency,p.subtotal,p.freight_cost,p.additional_cost from public.purchase_orders p where p.organization_id=target_organization_id;end$$;
create function public.get_purchase_order_line_costs(target_organization_id uuid,target_purchase_order_id uuid) returns table(id uuid,unit_cost numeric,currency text) language plpgsql security definer set search_path='' as $$begin perform private.require_phase3c_org(target_organization_id,'purchasing.view_costs');return query select l.id,l.unit_cost,l.currency from public.purchase_order_lines l where l.organization_id=target_organization_id and l.purchase_order_id=target_purchase_order_id;end$$;
create function public.get_supplier_issue_credits(target_organization_id uuid) returns table(id uuid,credit_amount numeric,currency text) language plpgsql security definer set search_path='' as $$begin perform private.require_phase3c_org(target_organization_id,'purchasing.view_costs');return query select i.id,i.credit_amount,i.currency from public.supplier_issues i where i.organization_id=target_organization_id;end$$;
revoke all on function public.get_purchase_order_costs(uuid),public.get_purchase_order_line_costs(uuid,uuid),public.get_supplier_issue_credits(uuid) from public,anon;
grant execute on function public.get_purchase_order_costs(uuid),public.get_purchase_order_line_costs(uuid,uuid),public.get_supplier_issue_credits(uuid) to authenticated;

create function public.admin_save_purchase_order(target_id uuid,target_organization_id uuid,target_supplier_id uuid,target_number text,target_supplier_reference text,target_order_date date,target_expected_ship date,target_expected_delivery date,target_currency text,target_subtotal numeric,target_freight numeric,target_additional numeric,target_status public.purchase_order_status,target_notes text,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'purchasing.manage');rid uuid;begin
 if not private.has_permission(target_organization_id,'purchasing.view_costs',actor) and (coalesce(target_subtotal,0)<>0 or coalesce(target_freight,0)<>0 or coalesce(target_additional,0)<>0) then raise exception'Cost permission required' using errcode='42501';end if;
 if not exists(select 1 from public.suppliers where id=target_supplier_id and organization_id=target_organization_id and status='active') then raise exception'Invalid supplier' using errcode='22023';end if;
 if target_id is null and target_idempotency_key is not null then select id into rid from public.purchase_orders where organization_id=target_organization_id and idempotency_key=target_idempotency_key;if rid is not null then return rid;end if;end if;
 if target_id is null then insert into public.purchase_orders(organization_id,supplier_id,purchase_order_number,supplier_reference,order_date,expected_ship_date,expected_delivery_date,currency,subtotal,freight_cost,additional_cost,status,internal_notes,created_by,idempotency_key) values(target_organization_id,target_supplier_id,trim(target_number),nullif(trim(target_supplier_reference),''),target_order_date,target_expected_ship,target_expected_delivery,upper(target_currency),coalesce(target_subtotal,0),coalesce(target_freight,0),coalesce(target_additional,0),target_status,nullif(trim(target_notes),''),actor,target_idempotency_key) returning id into rid;
 else update public.purchase_orders set supplier_reference=nullif(trim(target_supplier_reference),''),order_date=target_order_date,expected_ship_date=target_expected_ship,expected_delivery_date=target_expected_delivery,status=target_status,internal_notes=nullif(trim(target_notes),''),subtotal=case when private.has_permission(target_organization_id,'purchasing.view_costs',actor) then coalesce(target_subtotal,subtotal) else subtotal end,freight_cost=case when private.has_permission(target_organization_id,'purchasing.view_costs',actor) then coalesce(target_freight,freight_cost) else freight_cost end,additional_cost=case when private.has_permission(target_organization_id,'purchasing.view_costs',actor) then coalesce(target_additional,additional_cost) else additional_cost end,updated_at=now() where id=target_id and organization_id=target_organization_id and supplier_id=target_supplier_id returning id into rid; if rid is null then raise exception'PO not found' using errcode='P0002';end if;end if;
 perform private.write_audit_event(actor,target_organization_id,case when target_id is null then'purchase_order.created'else'purchase_order.updated'end,'purchase_order',rid::text,jsonb_build_object('status',target_status));return rid;end$$;

create function public.admin_save_purchase_order_line(target_id uuid,target_organization_id uuid,target_purchase_order_id uuid,target_supplier_product_variant_id uuid,target_quantity numeric,target_unit_cost numeric,target_currency text,target_expected_lot text,target_expected_expiration date,target_expected_bud date,target_expected_delivery date,target_notes text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'purchasing.manage');rid uuid;variant uuid;begin
 if not private.has_permission(target_organization_id,'purchasing.view_costs',actor) then raise exception'Cost permission required' using errcode='42501';end if;
 select spv.product_variant_id into variant from public.supplier_product_variants spv join public.purchase_orders po on po.supplier_id=spv.supplier_id and po.organization_id=spv.organization_id where spv.id=target_supplier_product_variant_id and spv.organization_id=target_organization_id and po.id=target_purchase_order_id; if variant is null then raise exception'Invalid supplier/product relationship' using errcode='22023';end if;
 if target_id is null then insert into public.purchase_order_lines(organization_id,purchase_order_id,supplier_product_variant_id,product_variant_id,supplier_sku,quantity_ordered,unit_cost,currency,expected_lot,expected_expiration,expected_bud,expected_delivery_date,notes) select target_organization_id,target_purchase_order_id,spv.id,spv.product_variant_id,spv.supplier_sku,target_quantity,target_unit_cost,upper(target_currency),nullif(trim(target_expected_lot),''),target_expected_expiration,target_expected_bud,target_expected_delivery,nullif(trim(target_notes),'') from public.supplier_product_variants spv where spv.id=target_supplier_product_variant_id returning id into rid;
 else update public.purchase_order_lines set quantity_ordered=target_quantity,unit_cost=target_unit_cost,currency=upper(target_currency),expected_lot=nullif(trim(target_expected_lot),''),expected_expiration=target_expected_expiration,expected_bud=target_expected_bud,expected_delivery_date=target_expected_delivery,notes=nullif(trim(target_notes),''),updated_at=now() where id=target_id and organization_id=target_organization_id and purchase_order_id=target_purchase_order_id and supplier_product_variant_id=target_supplier_product_variant_id returning id into rid;if rid is null then raise exception'PO line not found' using errcode='P0002';end if;end if;
 perform private.write_audit_event(actor,target_organization_id,case when target_id is null then'purchase_order_line.created'else'purchase_order_line.updated'end,'purchase_order_line',rid::text,jsonb_build_object('purchase_order_id',target_purchase_order_id));return rid;end$$;

create function public.admin_save_inbound_shipment(target_id uuid,target_organization_id uuid,target_supplier_id uuid,target_purchase_order_id uuid,target_reference text,target_carrier text,target_tracking text,target_expected date,target_actual timestamptz,target_status public.inbound_shipment_status,target_packages integer,target_warehouse_id uuid,target_notes text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'purchasing.manage');rid uuid;begin
 if not exists(select 1 from public.suppliers s where s.id=target_supplier_id and s.organization_id=target_organization_id) or (target_purchase_order_id is not null and not exists(select 1 from public.purchase_orders where id=target_purchase_order_id and organization_id=target_organization_id and supplier_id=target_supplier_id)) then raise exception'Invalid procurement relationship' using errcode='22023';end if;
 if target_id is null then insert into public.inbound_shipments(organization_id,supplier_id,purchase_order_id,shipment_reference,carrier,tracking_number,expected_arrival_date,actual_arrival_at,status,package_count,warehouse_id,notes,created_by) values(target_organization_id,target_supplier_id,target_purchase_order_id,trim(target_reference),nullif(trim(target_carrier),''),nullif(trim(target_tracking),''),target_expected,target_actual,target_status,target_packages,target_warehouse_id,nullif(trim(target_notes),''),actor) returning id into rid;
 else update public.inbound_shipments set purchase_order_id=target_purchase_order_id,carrier=nullif(trim(target_carrier),''),tracking_number=nullif(trim(target_tracking),''),expected_arrival_date=target_expected,actual_arrival_at=target_actual,status=target_status,package_count=target_packages,warehouse_id=target_warehouse_id,notes=nullif(trim(target_notes),''),updated_at=now() where id=target_id and organization_id=target_organization_id and supplier_id=target_supplier_id returning id into rid;if rid is null then raise exception'Shipment not found' using errcode='P0002';end if;end if;
 perform private.write_audit_event(actor,target_organization_id,case when target_id is null then'inbound_shipment.created'else'inbound_shipment.updated'end,'inbound_shipment',rid::text,jsonb_build_object('status',target_status));return rid;end$$;

create function public.admin_receive_purchase_order(target_organization_id uuid,target_purchase_order_line_id uuid,target_inbound_shipment_id uuid,target_warehouse_id uuid,target_location_id uuid,target_lot_number text,target_expiration date,target_bud date,target_quantity numeric,target_accepted numeric,target_damaged numeric,target_rejected numeric,target_qc_required boolean,target_reference text,target_reason text,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'receiving.manage');line public.purchase_order_lines%rowtype;po public.purchase_orders%rowtype;lotid uuid;receivingid uuid;eligible numeric;begin
 if target_quantity<=0 or target_accepted<0 or target_damaged<0 or target_rejected<0 or target_accepted+target_damaged+target_rejected<>target_quantity then raise exception'Invalid receiving quantities' using errcode='22023';end if;
 select * into line from public.purchase_order_lines where id=target_purchase_order_line_id and organization_id=target_organization_id for update; if line.id is null then raise exception'PO line not found' using errcode='22023';end if; select * into po from public.purchase_orders where id=line.purchase_order_id for update;
 if target_inbound_shipment_id is not null and not exists(select 1 from public.inbound_shipments where id=target_inbound_shipment_id and organization_id=target_organization_id and (purchase_order_id is null or purchase_order_id=po.id) and supplier_id=po.supplier_id) then raise exception'Invalid shipment' using errcode='22023';end if;
 select id into receivingid from public.receivings where organization_id=target_organization_id and idempotency_key=target_idempotency_key;if receivingid is not null then return receivingid;end if;
 insert into public.inventory_lots(organization_id,product_variant_id,lot_number,expiration_date,bud_date,quantity_received,unit_of_measure,status,received_date) values(target_organization_id,line.product_variant_id,trim(target_lot_number),target_expiration,target_bud,0,'each',case when target_expiration<current_date or target_bud<current_date then'expired'::public.lot_status when target_qc_required then'pending_qc'::public.lot_status else'available'::public.lot_status end,current_date) on conflict(organization_id,product_variant_id,lot_number) do update set expiration_date=coalesce(public.inventory_lots.expiration_date,excluded.expiration_date),bud_date=coalesce(public.inventory_lots.bud_date,excluded.bud_date) returning id into lotid;
 insert into public.receivings(organization_id,warehouse_id,receiving_reference,received_at,received_by_user_id,status,idempotency_key,purchase_order_id,inbound_shipment_id,notes) values(target_organization_id,target_warehouse_id,trim(target_reference),now(),actor,'completed',target_idempotency_key,po.id,target_inbound_shipment_id,nullif(trim(target_reason),'')) returning id into receivingid;
 insert into public.receiving_lines(organization_id,receiving_id,product_variant_id,lot_id,destination_location_id,quantity_expected,quantity_received,discrepancy_quantity,discrepancy_reason,status,expiration_date,bud_date,purchase_order_line_id,quantity_accepted,quantity_damaged,quantity_rejected,qc_required) values(target_organization_id,receivingid,line.product_variant_id,lotid,target_location_id,line.quantity_ordered-line.quantity_received,target_quantity,target_quantity-(line.quantity_ordered-line.quantity_received),nullif(trim(target_reason),''),case when target_quantity<>(line.quantity_ordered-line.quantity_received) or target_damaged>0 or target_rejected>0 then'discrepancy'::public.receiving_line_status else'received'::public.receiving_line_status end,target_expiration,target_bud,line.id,target_accepted,target_damaged,target_rejected,target_qc_required);
 eligible:=case when target_expiration<current_date or target_bud<current_date then 0 when target_qc_required then 0 else target_accepted end;
 perform private.apply_inventory_delta(target_organization_id,target_warehouse_id,target_location_id,line.product_variant_id,lotid,'receipt',target_quantity,eligible,0,case when target_qc_required then target_accepted else 0 end,target_damaged+target_rejected,'po_receiving',receivingid::text,actor,'PO receipt',target_idempotency_key,1);
 update public.inventory_lots set quantity_received=quantity_received+target_quantity where id=lotid; update public.purchase_order_lines set quantity_received=quantity_received+target_quantity,status=case when quantity_received+target_quantity>=quantity_ordered then'received'::public.purchase_order_line_status else'partially_received'::public.purchase_order_line_status end,updated_at=now() where id=line.id;
 update public.purchase_orders set status=case when not exists(select 1 from public.purchase_order_lines x where x.purchase_order_id=po.id and x.id<>line.id and x.status not in('received','closed','cancelled')) and line.quantity_received+target_quantity>=line.quantity_ordered then'received'::public.purchase_order_status else'partially_received'::public.purchase_order_status end,updated_at=now() where id=po.id;
 if target_inbound_shipment_id is not null then update public.inbound_shipments set status='partially_received',updated_at=now() where id=target_inbound_shipment_id;end if;
 perform private.write_audit_event(actor,target_organization_id,'receiving.completed','receiving',receivingid::text,jsonb_build_object('purchase_order_id',po.id,'accepted',target_accepted,'damaged',target_damaged,'rejected',target_rejected));return receivingid;end$$;

create function public.admin_record_qc_inspection(target_organization_id uuid,target_receiving_line_id uuid,target_lot_id uuid,target_warehouse_id uuid,target_location_id uuid,target_status public.qc_status,target_inspected numeric,target_approved numeric,target_quarantined numeric,target_rejected numeric,target_reason_code text,target_notes text,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'qc.inspect');rid uuid;line public.receiving_lines%rowtype;begin
 if target_inspected<=0 or target_approved+target_quarantined+target_rejected<>target_inspected then raise exception'Invalid QC quantities' using errcode='22023';end if;select*into line from public.receiving_lines where id=target_receiving_line_id and organization_id=target_organization_id and lot_id=target_lot_id for update;if line.id is null then raise exception'Invalid receiving line' using errcode='22023';end if;
 select id into rid from public.qc_inspections where organization_id=target_organization_id and idempotency_key=target_idempotency_key;if rid is not null then return rid;end if;
 insert into public.qc_inspections(organization_id,receiving_id,receiving_line_id,lot_id,inbound_shipment_id,inspector_user_id,status,quantity_inspected,quantity_approved,quantity_quarantined,quantity_rejected,reason_code,notes,idempotency_key) select target_organization_id,line.receiving_id,line.id,line.lot_id,r.inbound_shipment_id,actor,target_status,target_inspected,target_approved,target_quarantined,target_rejected,nullif(trim(target_reason_code),''),nullif(trim(target_notes),''),target_idempotency_key from public.receivings r where r.id=line.receiving_id returning id into rid;
 if target_rejected>0 then perform private.apply_inventory_delta(target_organization_id,target_warehouse_id,target_location_id,line.product_variant_id,line.lot_id,'damage',0,0,0,-target_rejected,target_rejected,'qc_inspection',rid::text,actor,'QC rejected',target_idempotency_key,1);end if;
 update public.inventory_lots set status=case when target_status in('failed','rejected') then'rejected'::public.lot_status when target_status in('passed','partial_pass') then'pending_qc'::public.lot_status else'quarantined'::public.lot_status end where id=line.lot_id;
 perform private.write_audit_event(actor,target_organization_id,'qc.inspected','qc_inspection',rid::text,jsonb_build_object('status',target_status,'approved',target_approved,'rejected',target_rejected));return rid;end$$;

create function public.admin_release_qc_inventory(target_organization_id uuid,target_qc_inspection_id uuid,target_warehouse_id uuid,target_location_id uuid,target_quantity numeric,target_idempotency_key text) returns bigint language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'qc.release');q public.qc_inspections%rowtype;l public.inventory_lots%rowtype;tx bigint;begin
 select*into q from public.qc_inspections where id=target_qc_inspection_id and organization_id=target_organization_id for update;if q.id is null or q.status not in('passed','partial_pass') then raise exception'QC approval required' using errcode='22023';end if;select*into l from public.inventory_lots where id=q.lot_id for update;if l.status in('rejected','expired','recalled') or l.expiration_date<current_date or l.bud_date<current_date then raise exception'Lot ineligible for release' using errcode='22023';end if;if target_quantity<=0 or target_quantity>q.quantity_approved then raise exception'Invalid release quantity' using errcode='22023';end if;
 tx:=private.apply_inventory_delta(target_organization_id,target_warehouse_id,target_location_id,l.product_variant_id,l.id,'release_quarantine',0,target_quantity,0,-target_quantity,0,'qc_release',q.id::text,actor,'QC release',target_idempotency_key,1);update public.qc_inspections set status='released',updated_at=now() where id=q.id;update public.inventory_lots set status='available',updated_at=now() where id=l.id;perform private.write_audit_event(actor,target_organization_id,'qc.inventory_released','qc_inspection',q.id::text,jsonb_build_object('quantity',target_quantity,'transaction_id',tx));return tx;end$$;

create function public.admin_save_quality_document(target_id uuid,target_organization_id uuid,target_lot_id uuid,target_type text,target_name text,target_laboratory text,target_report text,target_test_date date,target_status public.quality_document_status,target_notes text,target_storage_reference text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'quality_documents.manage');rid uuid;begin if not exists(select 1 from public.inventory_lots where id=target_lot_id and organization_id=target_organization_id) then raise exception'Invalid lot' using errcode='22023';end if;if target_id is null then insert into public.quality_documents(organization_id,lot_id,document_type,document_name,testing_laboratory,report_reference,test_date,status,notes,storage_reference,created_by) values(target_organization_id,target_lot_id,target_type,trim(target_name),nullif(trim(target_laboratory),''),nullif(trim(target_report),''),target_test_date,target_status,nullif(trim(target_notes),''),nullif(trim(target_storage_reference),''),actor) returning id into rid;else update public.quality_documents set document_name=trim(target_name),testing_laboratory=nullif(trim(target_laboratory),''),report_reference=nullif(trim(target_report),''),test_date=target_test_date,status=target_status,notes=nullif(trim(target_notes),''),storage_reference=nullif(trim(target_storage_reference),''),updated_at=now() where id=target_id and organization_id=target_organization_id and lot_id=target_lot_id returning id into rid;if rid is null then raise exception'Document not found' using errcode='P0002';end if;end if;perform private.write_audit_event(actor,target_organization_id,case when target_id is null then'quality_document.created'else'quality_document.updated'end,'quality_document',rid::text,jsonb_build_object('type',target_type,'status',target_status));return rid;end$$;

create function public.admin_save_supplier_issue(target_id uuid,target_organization_id uuid,target_supplier_id uuid,target_purchase_order_id uuid,target_receiving_id uuid,target_inbound_shipment_id uuid,target_lot_id uuid,target_issue_type text,target_quantity numeric,target_severity public.supplier_issue_severity,target_description text,target_status public.supplier_issue_status,target_supplier_notified timestamptz,target_owner uuid,target_resolution text,target_resolution_type public.supplier_resolution_type,target_replacement_quantity numeric,target_replacement_expected date,target_credit_amount numeric,target_currency text,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid:=private.require_phase3c_org(target_organization_id,'supplier_issues.manage');rid uuid;begin
 if not exists(select 1 from public.suppliers where id=target_supplier_id and organization_id=target_organization_id) then raise exception'Invalid supplier' using errcode='22023';end if;if target_credit_amount is not null and not private.has_permission(target_organization_id,'purchasing.view_costs',actor) then raise exception'Cost permission required' using errcode='42501';end if;
 if target_id is null then insert into public.supplier_issues(organization_id,supplier_id,purchase_order_id,receiving_id,inbound_shipment_id,lot_id,issue_type,quantity_affected,severity,description,status,supplier_notified_at,internal_owner_user_id,resolution,resolution_type,replacement_quantity,replacement_expected_date,credit_amount,currency,resolved_at,created_by,idempotency_key) values(target_organization_id,target_supplier_id,target_purchase_order_id,target_receiving_id,target_inbound_shipment_id,target_lot_id,target_issue_type,target_quantity,target_severity,trim(target_description),target_status,target_supplier_notified,target_owner,nullif(trim(target_resolution),''),target_resolution_type,target_replacement_quantity,target_replacement_expected,target_credit_amount,case when target_currency is null then null else upper(target_currency) end,case when target_status in('resolved','closed') then now() end,actor,target_idempotency_key) returning id into rid;
 else update public.supplier_issues set status=target_status,supplier_notified_at=target_supplier_notified,internal_owner_user_id=target_owner,resolution=nullif(trim(target_resolution),''),resolution_type=target_resolution_type,replacement_quantity=target_replacement_quantity,replacement_expected_date=target_replacement_expected,credit_amount=case when private.has_permission(target_organization_id,'purchasing.view_costs',actor) then target_credit_amount else credit_amount end,currency=case when target_currency is null then currency else upper(target_currency) end,resolved_at=case when target_status in('resolved','closed') then coalesce(resolved_at,now()) else null end,updated_at=now() where id=target_id and organization_id=target_organization_id and supplier_id=target_supplier_id returning id into rid;if rid is null then raise exception'Issue not found' using errcode='P0002';end if;end if;
 perform private.write_audit_event(actor,target_organization_id,case when target_id is null then'supplier_issue.created'else'supplier_issue.updated'end,'supplier_issue',rid::text,jsonb_build_object('status',target_status,'resolution_type',target_resolution_type));return rid;end$$;

revoke all on function public.admin_save_purchase_order(uuid,uuid,uuid,text,text,date,date,date,text,numeric,numeric,numeric,public.purchase_order_status,text,text),public.admin_save_purchase_order_line(uuid,uuid,uuid,uuid,numeric,numeric,text,text,date,date,date,text),public.admin_save_inbound_shipment(uuid,uuid,uuid,uuid,text,text,text,date,timestamptz,public.inbound_shipment_status,integer,uuid,text),public.admin_receive_purchase_order(uuid,uuid,uuid,uuid,uuid,text,date,date,numeric,numeric,numeric,numeric,boolean,text,text,text),public.admin_record_qc_inspection(uuid,uuid,uuid,uuid,uuid,public.qc_status,numeric,numeric,numeric,numeric,text,text,text),public.admin_release_qc_inventory(uuid,uuid,uuid,uuid,numeric,text),public.admin_save_quality_document(uuid,uuid,uuid,text,text,text,text,date,public.quality_document_status,text,text),public.admin_save_supplier_issue(uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,numeric,public.supplier_issue_severity,text,public.supplier_issue_status,timestamptz,uuid,text,public.supplier_resolution_type,numeric,date,numeric,text,text) from public,anon;
grant execute on function public.admin_save_purchase_order(uuid,uuid,uuid,text,text,date,date,date,text,numeric,numeric,numeric,public.purchase_order_status,text,text),public.admin_save_purchase_order_line(uuid,uuid,uuid,uuid,numeric,numeric,text,text,date,date,date,text),public.admin_save_inbound_shipment(uuid,uuid,uuid,uuid,text,text,text,date,timestamptz,public.inbound_shipment_status,integer,uuid,text),public.admin_receive_purchase_order(uuid,uuid,uuid,uuid,uuid,text,date,date,numeric,numeric,numeric,numeric,boolean,text,text,text),public.admin_record_qc_inspection(uuid,uuid,uuid,uuid,uuid,public.qc_status,numeric,numeric,numeric,numeric,text,text,text),public.admin_release_qc_inventory(uuid,uuid,uuid,uuid,numeric,text),public.admin_save_quality_document(uuid,uuid,uuid,text,text,text,text,date,public.quality_document_status,text,text),public.admin_save_supplier_issue(uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,numeric,public.supplier_issue_severity,text,public.supplier_issue_status,timestamptz,uuid,text,public.supplier_resolution_type,numeric,date,numeric,text,text) to authenticated;

commit;
