begin;

-- Phase 4C uses a namespaced permission hierarchy (for example fulfillment.picking.manage).
alter table public.permissions drop constraint permissions_code_check;
alter table public.permissions add constraint permissions_code_check check (code ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$');

insert into public.permissions(code,name,description) values
 ('fulfillment.picking.view','View pick lists','View internal picking queues and lot assignments'),
 ('fulfillment.picking.manage','Manage picking','Create pick lists and confirm picked quantities'),
 ('fulfillment.packing.view','View packing','View internal shipments and packages'),
 ('fulfillment.packing.manage','Manage packing','Create packages and correct contents before lock'),
 ('fulfillment.verify','Verify shipments','Perform final warehouse and pre-shipment eligibility verification'),
 ('fulfillment.shipments.view','View shipments','View internal shipment planning and history'),
 ('fulfillment.shipments.manage','Manage shipments','Plan split shipments and assign reservation chunks'),
 ('fulfillment.dispatch','Dispatch shipments','Confirm irreversible dispatch and fulfillment deduction'),
 ('fulfillment.exceptions.manage','Manage fulfillment exceptions','Resolve internal fulfillment holds and exceptions') on conflict do nothing;
insert into public.permissions(code,name,description) values
 ('fulfillment_picking.view','View pick lists','View internal picking queues and lot assignments'),
 ('fulfillment_picking.manage','Manage picking','Create pick lists and confirm picked quantities'),
 ('fulfillment_packing.view','View packing','View internal shipments and packages'),
 ('fulfillment_packing.manage','Manage packing','Create packages and correct contents before lock'),
 ('fulfillment_verify.manage','Verify shipments','Perform final warehouse and pre-shipment eligibility verification'),
 ('fulfillment_shipments.view','View shipments','View internal shipment planning and history'),
 ('fulfillment_shipments.manage','Manage shipments','Plan split shipments and assign reservation chunks'),
 ('fulfillment_dispatch.manage','Dispatch shipments','Confirm irreversible dispatch and fulfillment deduction'),
 ('fulfillment_exceptions.manage','Manage fulfillment exceptions','Resolve internal fulfillment holds and exceptions') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p
where r.code in('SUPER_ADMIN','ADMIN') and (p.code like 'fulfillment.%' or p.code like 'fulfillment_%') on conflict do nothing;

alter table public.order_allocations drop constraint if exists order_allocations_status_check;
alter table public.order_allocations add constraint order_allocations_status_check check(status in('reserved','released','fulfilled','cancelled'));

create table public.fulfillment_operation_runs(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,
 operation text not null,resource_id uuid,idempotency_key text not null,request_hash text not null,
 created_by_user_id uuid references auth.users(id),created_at timestamptz not null default now(),
 unique(organization_id,operation,idempotency_key)
);
create table public.pick_lists(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,
 client_organization_id uuid not null,order_id uuid not null,warehouse_id uuid not null,
 status text not null default 'draft' check(status in('draft','in_progress','partially_picked','picked','exception','cancelled')),
 version integer not null default 1,created_by_user_id uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(client_organization_id,order_id) references public.orders(client_organization_id,id),
 foreign key(organization_id,warehouse_id) references public.warehouses(organization_id,id),unique(organization_id,order_id,warehouse_id)
);
create table public.pick_list_lines(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null, pick_list_id uuid not null,order_line_id uuid not null,allocation_id uuid not null,
 product_variant_id uuid not null,lot_id uuid not null,warehouse_id uuid not null,location_id uuid not null,quantity_to_pick numeric(20,6) not null check(quantity_to_pick>0),quantity_picked numeric(20,6) not null default 0 check(quantity_picked>=0 and quantity_picked<=quantity_to_pick),
 status text not null default 'open' check(status in('open','picked','short','exception')),created_at timestamptz not null default now(),
 foreign key(pick_list_id) references public.pick_lists(id) on delete restrict,foreign key(order_line_id) references public.order_lines(id) on delete restrict,
 foreign key(allocation_id) references public.order_allocations(id) on delete restrict,foreign key(organization_id,warehouse_id,location_id) references public.warehouse_locations(organization_id,warehouse_id,id),
 foreign key(organization_id,product_variant_id,lot_id) references public.inventory_lots(organization_id,product_variant_id,id),unique(pick_list_id,allocation_id)
);
create table public.shipments(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,client_organization_id uuid not null,order_id uuid not null,
 shipment_sequence integer not null check(shipment_sequence>0 and shipment_sequence<100),status text not null default 'planned' check(status in('planned','picking','packed','warehouse_verified','ready_to_ship','dispatched','cancelled','exception')),
 version integer not null default 1,locked_at timestamptz,dispatched_at timestamptz,created_by_user_id uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(client_organization_id,order_id) references public.orders(client_organization_id,id),unique(order_id,shipment_sequence),unique(organization_id,id)
);
create table public.shipment_lines(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,shipment_id uuid not null,order_id uuid not null,order_line_id uuid not null,allocation_id uuid not null,
 product_variant_id uuid not null,lot_id uuid not null,warehouse_id uuid not null,location_id uuid not null,quantity numeric(20,6) not null check(quantity>0),created_at timestamptz not null default now(),
 foreign key(shipment_id) references public.shipments(id) on delete restrict,foreign key(order_line_id) references public.order_lines(id) on delete restrict,foreign key(allocation_id) references public.order_allocations(id) on delete restrict,
 foreign key(organization_id,warehouse_id,location_id) references public.warehouse_locations(organization_id,warehouse_id,id),foreign key(organization_id,product_variant_id,lot_id) references public.inventory_lots(organization_id,product_variant_id,id),
 unique(shipment_id,allocation_id)
);
create table public.shipment_packages(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,shipment_id uuid not null,package_sequence integer not null check(package_sequence>0),
 status text not null default 'open' check(status in('open','verified','locked')),weight numeric(20,6) check(weight is null or(weight>0 and weight<'Infinity'::numeric)),weight_unit text not null default 'lb' check(char_length(trim(weight_unit)) between 1 and 8),created_at timestamptz not null default now(),
 foreign key(shipment_id) references public.shipments(id) on delete restrict,unique(shipment_id,package_sequence)
);
create table public.shipment_package_contents(
 id uuid primary key default extensions.gen_random_uuid(),package_id uuid not null,shipment_line_id uuid not null,quantity numeric(20,6) not null check(quantity>0),created_at timestamptz not null default now(),
 foreign key(package_id) references public.shipment_packages(id) on delete restrict,foreign key(shipment_line_id) references public.shipment_lines(id) on delete restrict,unique(package_id,shipment_line_id)
);
create table public.warehouse_verifications(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,shipment_id uuid not null,status text not null default 'pending' check(status in('pending','passed','failed','hold')),
 expected_quantity numeric(20,6) not null default 0 check(expected_quantity>=0),verified_quantity numeric(20,6) not null default 0 check(verified_quantity>=0),notes text not null default '',verified_by_user_id uuid references auth.users(id),verified_at timestamptz,version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(shipment_id) references public.shipments(id) on delete restrict,unique(shipment_id)
);
create table public.warehouse_verification_events(
 id bigint generated always as identity primary key,organization_id uuid not null,shipment_id uuid not null,warehouse_verification_id uuid not null,status text not null,notes text not null default '',actor_user_id uuid not null references auth.users(id),created_at timestamptz not null default now(),
 foreign key(warehouse_verification_id) references public.warehouse_verifications(id) on delete restrict,foreign key(shipment_id) references public.shipments(id) on delete restrict
);
create table public.shipment_verifications(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,client_organization_id uuid not null,order_id uuid not null,shipment_id uuid not null,
 verification_number text not null unique,shipment_sequence integer not null,fulfillment_status text not null,snapshot jsonb not null,created_by_user_id uuid not null references auth.users(id),created_at timestamptz not null default now(),
 foreign key(shipment_id) references public.shipments(id) on delete restrict,foreign key(client_organization_id,order_id) references public.orders(client_organization_id,id),unique(shipment_id),unique(order_id,shipment_sequence)
);

do $$declare t text;begin foreach t in array array['fulfillment_operation_runs','pick_lists','pick_list_lines','shipments','shipment_lines','shipment_packages','shipment_package_contents','warehouse_verifications','warehouse_verification_events','shipment_verifications'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant all on public.%I to service_role',t);end loop;end $$;
create policy pick_internal_read on public.pick_lists for select to authenticated using(private.has_permission(organization_id,'fulfillment_picking.view'));
create policy pick_line_internal_read on public.pick_list_lines for select to authenticated using(private.has_permission(organization_id,'fulfillment_picking.view'));
create policy shipment_internal_read on public.shipments for select to authenticated using(private.has_permission(organization_id,'fulfillment_shipments.view'));
create policy shipment_line_internal_read on public.shipment_lines for select to authenticated using(private.has_permission(organization_id,'fulfillment_shipments.view'));
create policy package_internal_read on public.shipment_packages for select to authenticated using(private.has_permission(organization_id,'fulfillment_packing.view'));
create policy package_content_internal_read on public.shipment_package_contents for select to authenticated using(exists(select 1 from public.shipment_packages p where p.id=package_id and private.has_permission(p.organization_id,'fulfillment_packing.view')));
create policy warehouse_verification_internal_read on public.warehouse_verifications for select to authenticated using(private.has_permission(organization_id,'fulfillment_verify.manage'));
create policy warehouse_verification_event_internal_read on public.warehouse_verification_events for select to authenticated using(private.has_permission(organization_id,'fulfillment_verify.manage'));
create policy shipment_verification_read on public.shipment_verifications for select to authenticated using(private.can_access_order(client_organization_id,organization_id,'orders.view'));
grant select on public.pick_lists,public.pick_list_lines,public.shipments,public.shipment_lines,public.shipment_packages,public.shipment_package_contents,public.warehouse_verifications,public.warehouse_verification_events,public.shipment_verifications to authenticated;

create function private.fulfillment_hash(payload jsonb) returns text language sql immutable set search_path='' as $$select encode(extensions.digest(convert_to(payload::text,'UTF8'),'sha256'),'hex')$$;
revoke all on function private.fulfillment_hash(jsonb) from public,anon,authenticated;

create function public.admin_create_pick_list(target_order_id uuid,target_warehouse_id uuid,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare o public.orders;rid uuid;begin
 perform private.require_inventory_org((select organization_id from public.orders where id=target_order_id),'fulfillment.picking.manage',auth.uid());
 select * into o from public.orders where id=target_order_id for update;if o.id is null or not private.can_access_order(o.client_organization_id,o.organization_id,'orders.manage') or o.status not in('submitted','accepted') then raise exception'Order not eligible for picking'using errcode='42501';end if;
 if length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid pick request'using errcode='22023';end if;
 select resource_id into rid from public.fulfillment_operation_runs where organization_id=o.organization_id and operation='pick_list' and idempotency_key=trim(target_idempotency_key) for update;if rid is not null then return rid;end if;
 if not exists(select 1 from public.warehouses where id=target_warehouse_id and organization_id=o.organization_id and status='active') then raise exception'Invalid warehouse'using errcode='22023';end if;
 insert into public.pick_lists(organization_id,client_organization_id,order_id,warehouse_id,created_by_user_id)values(o.organization_id,o.client_organization_id,o.id,target_warehouse_id,auth.uid())returning id into rid;
 insert into public.pick_list_lines(organization_id,pick_list_id,order_line_id,allocation_id,product_variant_id,lot_id,warehouse_id,location_id,quantity_to_pick)
 select o.organization_id,rid,oa.order_line_id,oa.id,oa.product_variant_id,oa.lot_id,oa.warehouse_id,oa.location_id,oa.quantity from public.order_allocations oa where oa.order_id=o.id and oa.organization_id=o.organization_id and oa.warehouse_id=target_warehouse_id and oa.status='reserved';
 if not exists(select 1 from public.pick_list_lines where pick_list_id=rid) then raise exception'No active reservations for warehouse'using errcode='22023';end if;
 insert into public.fulfillment_operation_runs(organization_id,operation,resource_id,idempotency_key,request_hash,created_by_user_id)values(o.organization_id,'pick_list',rid,trim(target_idempotency_key),private.fulfillment_hash(jsonb_build_object('order',o.id,'warehouse',target_warehouse_id)),auth.uid());
 perform private.write_audit_event(auth.uid(),o.organization_id,'fulfillment.pick_list_created','pick_list',rid::text,jsonb_build_object('order_id',o.id,'warehouse_id',target_warehouse_id));return rid;end $$;

create function public.admin_confirm_pick_line(target_pick_list_id uuid,target_pick_line_id uuid,target_quantity numeric,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare p public.pick_lists;l public.pick_list_lines;rid uuid;begin
 select * into p from public.pick_lists where id=target_pick_list_id for update;if p.id is null or not private.has_permission(p.organization_id,'fulfillment.picking.manage') or not private.can_access_order(p.client_organization_id,p.organization_id,'orders.manage') then raise exception'Not authorized'using errcode='42501';end if;
 if length(trim(coalesce(target_idempotency_key,'')))<8 or target_quantity is null or target_quantity<0 or target_quantity>100000000 then raise exception'Invalid pick quantity'using errcode='22023';end if;
 select resource_id into rid from public.fulfillment_operation_runs where organization_id=p.organization_id and operation='pick_confirm' and idempotency_key=trim(target_idempotency_key) for update;if rid is not null then return rid;end if;
 select * into l from public.pick_list_lines where id=target_pick_line_id and pick_list_id=p.id for update;if l.id is null then raise exception'Pick line not found'using errcode='P0002';end if;if target_quantity>l.quantity_to_pick then raise exception'Picked quantity exceeds reservation'using errcode='22023';end if;
 update public.pick_list_lines set quantity_picked=target_quantity,status=case when target_quantity=l.quantity_to_pick then'picked'when target_quantity=0 then'open'else'short'end where id=l.id;
 update public.pick_lists set status=case when not exists(select 1 from public.pick_list_lines where pick_list_id=p.id and quantity_picked<quantity_to_pick)then'picked'when exists(select 1 from public.pick_list_lines where pick_list_id=p.id and quantity_picked>0)then'partially_picked'else'in_progress'end,version=version+1,updated_at=now()where id=p.id;
  insert into public.fulfillment_operation_runs(organization_id,operation,resource_id,idempotency_key,request_hash,created_by_user_id)values(p.organization_id,'pick_confirm',l.id,trim(target_idempotency_key),private.fulfillment_hash(jsonb_build_object('pick_line',l.id,'quantity',target_quantity)),auth.uid());perform private.write_audit_event(auth.uid(),p.organization_id,'fulfillment.pick_confirmed','pick_list_line',l.id::text,jsonb_build_object('quantity',target_quantity,'lot_id',l.lot_id,'location_id',l.location_id));return l.id;end $$;

create function public.admin_create_shipment(target_order_id uuid,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare o public.orders;rid uuid;seq integer;begin
 select * into o from public.orders where id=target_order_id for update;if o.id is null or not private.has_permission(o.organization_id,'fulfillment.shipments.manage') or not private.can_access_order(o.client_organization_id,o.organization_id,'orders.manage') or o.status not in('submitted','accepted','processing') then raise exception'Order not eligible for shipment planning'using errcode='42501';end if;
 if length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid shipment request'using errcode='22023';end if;
 select resource_id into rid from public.fulfillment_operation_runs where organization_id=o.organization_id and operation='shipment' and idempotency_key=trim(target_idempotency_key) for update;if rid is not null then return rid;end if;
 select coalesce(max(shipment_sequence),0)+1 into seq from public.shipments where order_id=o.id;if seq>=100 then raise exception'Shipment sequence exhausted'using errcode='22003';end if;
 insert into public.shipments(organization_id,client_organization_id,order_id,shipment_sequence,created_by_user_id)values(o.organization_id,o.client_organization_id,o.id,seq,auth.uid())returning id into rid;
 update public.orders set status='processing',version=version+1,updated_at=now() where id=o.id and status in('submitted','accepted');
 insert into public.fulfillment_operation_runs(organization_id,operation,resource_id,idempotency_key,request_hash,created_by_user_id)values(o.organization_id,'shipment',rid,trim(target_idempotency_key),private.fulfillment_hash(jsonb_build_object('order',o.id,'sequence',seq)),auth.uid());
 perform private.write_audit_event(auth.uid(),o.organization_id,'fulfillment.shipment_created','shipment',rid::text,jsonb_build_object('order_id',o.id,'shipment_sequence',seq));return rid;end $$;

create function public.admin_assign_shipment_allocation(target_shipment_id uuid,target_allocation_id uuid,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare s public.shipments;a public.order_allocations;rid uuid;assigned numeric;begin
 select * into s from public.shipments where id=target_shipment_id for update;if s.id is null or s.status not in('planned','picking','packed') or not private.has_permission(s.organization_id,'fulfillment.shipments.manage') or not private.can_access_order(s.client_organization_id,s.organization_id,'orders.manage') then raise exception'Not authorized or shipment locked'using errcode='42501';end if;
 if length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid shipment assignment'using errcode='22023';end if;
 select resource_id into rid from public.fulfillment_operation_runs where organization_id=s.organization_id and operation='shipment_line' and idempotency_key=trim(target_idempotency_key) for update;if rid is not null then return rid;end if;
 select * into a from public.order_allocations where id=target_allocation_id and order_id=s.order_id and organization_id=s.organization_id for update;if a.id is null or a.status<>'reserved' then raise exception'Active allocation required'using errcode='22023';end if;
 if exists(select 1 from public.shipment_lines where allocation_id=a.id) then raise exception'Allocation already assigned to a shipment'using errcode='22023';end if;
 select coalesce(sum(quantity),0) into assigned from public.shipment_lines where order_line_id=a.order_line_id and order_id=s.order_id;if assigned+a.quantity>(select quantity from public.order_lines where id=a.order_line_id) then raise exception'Shipment assignment exceeds order quantity'using errcode='22023';end if;
 insert into public.shipment_lines(organization_id,shipment_id,order_id,order_line_id,allocation_id,product_variant_id,lot_id,warehouse_id,location_id,quantity)values(a.organization_id,s.id,s.order_id,a.order_line_id,a.id,a.product_variant_id,a.lot_id,a.warehouse_id,a.location_id,a.quantity)returning id into rid;
 update public.shipments set status='picking',version=version+1,updated_at=now()where id=s.id;insert into public.fulfillment_operation_runs(organization_id,operation,resource_id,idempotency_key,request_hash,created_by_user_id)values(s.organization_id,'shipment_line',rid,trim(target_idempotency_key),private.fulfillment_hash(jsonb_build_object('shipment',s.id,'allocation',a.id)),auth.uid());perform private.write_audit_event(auth.uid(),s.organization_id,'fulfillment.shipment_line_assigned','shipment_line',rid::text,jsonb_build_object('allocation_id',a.id,'quantity',a.quantity));return rid;end $$;

create function public.admin_create_shipment_package(target_shipment_id uuid,target_weight numeric,target_weight_unit text,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
 declare s public.shipments;rid uuid;seq integer;begin select * into s from public.shipments where id=target_shipment_id for update;if s.id is null or s.status not in('planned','picking','packed') or not private.has_permission(s.organization_id,'fulfillment_packing.manage') then raise exception'Not authorized or shipment locked'using errcode='42501';end if;if target_weight is not null and target_weight<=0 then raise exception'Invalid package weight'using errcode='22023';end if;if length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid package request'using errcode='22023';end if;select resource_id into rid from public.fulfillment_operation_runs where organization_id=s.organization_id and operation='package' and idempotency_key=trim(target_idempotency_key) for update;if rid is not null then return rid;end if;select coalesce(max(package_sequence),0)+1 into seq from public.shipment_packages where shipment_id=s.id;insert into public.shipment_packages(organization_id,shipment_id,package_sequence,weight,weight_unit)values(s.organization_id,s.id,seq,target_weight,coalesce(nullif(trim(target_weight_unit),''),'lb'))returning id into rid;update public.shipments set status='packed',version=version+1,updated_at=now()where id=s.id;insert into public.fulfillment_operation_runs(organization_id,operation,resource_id,idempotency_key,request_hash,created_by_user_id)values(s.organization_id,'package',rid,trim(target_idempotency_key),private.fulfillment_hash(jsonb_build_object('shipment',s.id,'weight',target_weight)),auth.uid());perform private.write_audit_event(auth.uid(),s.organization_id,'fulfillment.package_created','shipment_package',rid::text,jsonb_build_object('shipment_id',s.id,'weight',target_weight,'unit',target_weight_unit));return rid;end $$;

create function public.admin_set_package_content(target_package_id uuid,target_shipment_line_id uuid,target_quantity numeric,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare p public.shipment_packages;l public.shipment_lines;rid uuid;used numeric;begin select * into p from public.shipment_packages where id=target_package_id for update;if p.id is null or p.status<>'open' or not private.has_permission(p.organization_id,'fulfillment.packing.manage') then raise exception'Package is locked or unauthorized'using errcode='42501';end if;if length(trim(coalesce(target_idempotency_key,'')))<8 or target_quantity is null or target_quantity<=0 then raise exception'Invalid package content'using errcode='22023';end if;select resource_id into rid from public.fulfillment_operation_runs where organization_id=p.organization_id and operation='package_content' and idempotency_key=trim(target_idempotency_key) for update;if rid is not null then return rid;end if;select * into l from public.shipment_lines where id=target_shipment_line_id and shipment_id=p.shipment_id for share;if l.id is null then raise exception'Invalid package content'using errcode='22023';end if;select coalesce(sum(quantity),0) into used from public.shipment_package_contents where shipment_line_id=l.id and package_id<>p.id;if used+target_quantity>l.quantity then raise exception'Package content exceeds shipment quantity'using errcode='22023';end if;insert into public.shipment_package_contents(package_id,shipment_line_id,quantity)values(p.id,l.id,target_quantity)on conflict(package_id,shipment_line_id)do update set quantity=excluded.quantity returning id into rid;insert into public.fulfillment_operation_runs(organization_id,operation,resource_id,idempotency_key,request_hash,created_by_user_id)values(p.organization_id,'package_content',rid,trim(target_idempotency_key),private.fulfillment_hash(jsonb_build_object('package',p.id,'line',l.id,'quantity',target_quantity)),auth.uid());perform private.write_audit_event(auth.uid(),p.organization_id,'fulfillment.package_content_corrected','shipment_package_content',rid::text,jsonb_build_object('package_id',p.id,'shipment_line_id',l.id,'quantity',target_quantity));return rid;end $$;

create function public.admin_verify_shipment(target_shipment_id uuid,target_status text,target_verified_quantity numeric,target_notes text,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare s public.shipments;v public.warehouse_verifications;expected numeric;begin select * into s from public.shipments where id=target_shipment_id for update;if s.id is null or s.status in('ready_to_ship','dispatched','cancelled') or not private.has_permission(s.organization_id,'fulfillment.verify') then raise exception'Not authorized or shipment is locked'using errcode='42501';end if;if target_status not in('passed','failed','hold') or target_verified_quantity is null or target_verified_quantity<0 or length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid verification'using errcode='22023';end if;select coalesce(sum(quantity),0) into expected from public.shipment_lines where shipment_id=s.id;if target_status='passed' and target_verified_quantity<>expected then raise exception'Verified quantity must equal shipment contents'using errcode='22023';end if;if target_status='passed' and exists(select 1 from public.shipment_lines sl join public.inventory_lots lot on lot.id=sl.lot_id where sl.shipment_id=s.id and(lot.status<>'available'or lot.expiration_date<current_date or lot.bud_date<current_date))then raise exception'Ineligible lot cannot be verified'using errcode='42501';end if;if target_status='passed' and exists(select 1 from public.shipment_lines sl where sl.shipment_id=s.id and not exists(select 1 from public.pick_list_lines pl where pl.allocation_id=sl.allocation_id and pl.quantity_picked=pl.quantity_to_pick))then raise exception'Every allocation must be picked before verification'using errcode='22023';end if;
 insert into public.warehouse_verifications(organization_id,shipment_id,status,expected_quantity,verified_quantity,notes,verified_by_user_id,verified_at)values(s.organization_id,s.id,target_status,expected,target_verified_quantity,coalesce(target_notes,''),auth.uid(),now())on conflict(shipment_id)do update set status=excluded.status,expected_quantity=excluded.expected_quantity,verified_quantity=excluded.verified_quantity,notes=excluded.notes,verified_by_user_id=excluded.verified_by_user_id,verified_at=excluded.verified_at,version=public.warehouse_verifications.version+1,updated_at=now()returning * into v;
 insert into public.warehouse_verification_events(organization_id,shipment_id,warehouse_verification_id,status,notes,actor_user_id)values(s.organization_id,s.id,v.id,target_status,coalesce(target_notes,''),auth.uid());update public.shipments set status=case when target_status='passed'then'warehouse_verified'else'exception'end,version=version+1,updated_at=now()where id=s.id;perform private.write_audit_event(auth.uid(),s.organization_id,'fulfillment.shipment_verified','shipment',s.id::text,jsonb_build_object('status',target_status,'quantity',target_verified_quantity));return v.id;end $$;

create function public.admin_lock_shipment(target_shipment_id uuid,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare s public.shipments;v public.warehouse_verifications;seq text;num text;sv uuid;begin select * into s from public.shipments where id=target_shipment_id for update;if s.id is null or s.status<>'warehouse_verified' or not private.has_permission(s.organization_id,'fulfillment.verify') then raise exception'Shipment is not verified or authorized'using errcode='42501';end if;if exists(select 1 from public.shipment_packages p where p.shipment_id=s.id and(p.weight is null or p.weight<=0))or not exists(select 1 from public.shipment_packages p where p.shipment_id=s.id)then raise exception'Every shipment requires a positive package weight'using errcode='22023';end if;if exists(select 1 from public.shipment_lines sl where sl.shipment_id=s.id and not exists(select 1 from public.shipment_package_contents pc where pc.shipment_line_id=sl.id and pc.quantity=sl.quantity))then raise exception'Package contents must match shipment contents'using errcode='22023';end if;if length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid lock request'using errcode='22023';end if;if s.locked_at is not null then return s.id;end if;num:=right((select order_number from public.orders where id=s.order_id),6);seq:=lpad(s.shipment_sequence::text,2,'0');insert into public.shipment_verifications(organization_id,client_organization_id,order_id,shipment_id,verification_number,shipment_sequence,fulfillment_status,snapshot,created_by_user_id)values(s.organization_id,s.client_organization_id,s.order_id,s.id,'SVFC-'||num||'-'||seq,s.shipment_sequence,'ready_to_ship',jsonb_build_object('order_number',(select order_number from public.orders where id=s.order_id),'shipment_sequence',s.shipment_sequence,'shipment_contents',(select coalesce(jsonb_agg(jsonb_build_object('product',ol.display_name,'sku',ol.sku,'quantity',sl.quantity)order by sl.id),'[]')from public.shipment_lines sl join public.order_lines ol on ol.id=sl.order_line_id where sl.shipment_id=s.id),'packages',(select coalesce(jsonb_agg(jsonb_build_object('package_sequence',p.package_sequence,'weight',p.weight,'weight_unit',p.weight_unit)order by p.package_sequence),'[]')from public.shipment_packages p where p.shipment_id=s.id),'remaining_order_lines',(select coalesce(jsonb_agg(jsonb_build_object('product',ol.display_name,'sku',ol.sku,'remaining_quantity',greatest(0,ol.quantity-coalesce((select sum(x.quantity)from public.shipment_lines x join public.shipments xs on xs.id=x.shipment_id where x.order_line_id=ol.id and xs.status='dispatched'),0)))order by ol.id),'[]')from public.order_lines ol where ol.order_id=s.order_id)),auth.uid())on conflict(shipment_id)do nothing returning id into sv;
 update public.shipment_packages set status='locked'where shipment_id=s.id;update public.shipments set status='ready_to_ship',locked_at=now(),version=version+1,updated_at=now()where id=s.id;perform private.write_audit_event(auth.uid(),s.organization_id,'fulfillment.shipment_locked','shipment',s.id::text,jsonb_build_object('verification_number','SVFC-'||num||'-'||seq));return s.id;end $$;

create function public.admin_dispatch_shipment(target_shipment_id uuid,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare s public.shipments;line_rec record;ord public.orders;shipped numeric;ordered numeric;begin select * into s from public.shipments where id=target_shipment_id for update;if s.id is null or not private.has_permission(s.organization_id,'fulfillment.dispatch') then raise exception'Shipment is not ready or authorized'using errcode='42501';end if;if s.dispatched_at is not null then return s.id;end if;if s.status<>'ready_to_ship' or s.locked_at is null then raise exception'Shipment is not ready or authorized'using errcode='42501';end if;if length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid dispatch request'using errcode='22023';end if;
 for line_rec in select * from public.shipment_lines where shipment_id=s.id order by id for update loop
  perform private.apply_inventory_delta(line_rec.organization_id,line_rec.warehouse_id,line_rec.location_id,line_rec.product_variant_id,line_rec.lot_id,'fulfillment',-line_rec.quantity,0,-line_rec.quantity,0,0,'shipment',line_rec.id::text,auth.uid(),'Shipment dispatched','p4c-fulfill-'||line_rec.id::text,1);
  update public.inventory_reservations set status='fulfilled',fulfilled_at=now()where id=(select reservation_id from public.order_allocations where id=line_rec.allocation_id and status='reserved');
  update public.order_allocations set status='fulfilled'where id=line_rec.allocation_id and status='reserved';
 end loop;
 update public.shipments set status='dispatched',dispatched_at=now(),version=version+1,updated_at=now()where id=s.id;select * into ord from public.orders where id=s.order_id for update;
 select coalesce(sum(sline.quantity),0) into shipped from public.shipment_lines sline join public.shipments sx on sx.id=sline.shipment_id where sline.order_id=ord.id and sx.status='dispatched';select coalesce(sum(quantity),0) into ordered from public.order_lines where order_id=ord.id;
 update public.orders set status=case when shipped>=ordered then'fulfilled'::public.order_status else'partially_fulfilled'::public.order_status end,version=version+1,updated_at=now()where id=ord.id;
 perform private.write_audit_event(auth.uid(),s.organization_id,'fulfillment.shipment_dispatched','shipment',s.id::text,jsonb_build_object('physical_deduction',true,'quantity',shipped));return s.id;end $$;

create function public.admin_cancel_planned_shipment(target_shipment_id uuid,target_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare s public.shipments;sl record;begin select * into s from public.shipments where id=target_shipment_id for update;if s.id is null or s.status not in('planned','picking','packed','warehouse_verified','exception') or not private.has_permission(s.organization_id,'fulfillment.shipments.manage') then raise exception'Shipment cannot be cancelled at this stage'using errcode='42501';end if;if length(trim(coalesce(target_idempotency_key,'')))<8 then raise exception'Invalid cancellation request'using errcode='22023';end if;if s.status='cancelled' then return s.id;end if;
 for sl in select * from public.shipment_lines where shipment_id=s.id order by id for update loop
  perform private.apply_inventory_delta(sl.organization_id,sl.warehouse_id,sl.location_id,sl.product_variant_id,sl.lot_id,'release_reservation'::text,0::numeric,sl.quantity::numeric,-sl.quantity::numeric,0::numeric,0::numeric,'reservation'::text,(select reservation_id::text from public.order_allocations where id=sl.allocation_id),auth.uid(),'Shipment cancelled'::text,'p4c-cancel-'||sl.id::text,1);
  update public.inventory_reservations set status='released',released_at=now()where id=(select reservation_id from public.order_allocations where id=sl.allocation_id and status='reserved');update public.order_allocations set status='cancelled',released_at=now()where id=sl.allocation_id and status='reserved';
 end loop;update public.shipments set status='cancelled',version=version+1,updated_at=now()where id=s.id;perform private.write_audit_event(auth.uid(),s.organization_id,'fulfillment.shipment_cancelled','shipment',s.id::text,jsonb_build_object('reservations_released',true));return s.id;end $$;

create function public.get_order_fulfillment_summary(target_order_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare o public.orders;begin select * into o from public.orders where id=target_order_id;if o.id is null or not private.can_access_order(o.client_organization_id,o.organization_id,'orders.view') then raise exception'Not authorized'using errcode='42501';end if;return jsonb_build_object('order_number',o.order_number,'status',o.status,'allocation_status',o.allocation_status,'shipments',(select coalesce(jsonb_agg(jsonb_build_object('shipment_sequence',s.shipment_sequence,'status',s.status,'verification_number',(select sv.verification_number from public.shipment_verifications sv where sv.shipment_id=s.id),'contents',(select coalesce(jsonb_agg(jsonb_build_object('product',ol.display_name,'sku',ol.sku,'quantity',sl.quantity)order by sl.id),'[]')from public.shipment_lines sl join public.order_lines ol on ol.id=sl.order_line_id where sl.shipment_id=s.id))order by s.shipment_sequence),'[]')from public.shipments s where s.order_id=o.id and s.status<>'cancelled'),'remaining',(select coalesce(jsonb_agg(jsonb_build_object('product',l.display_name,'sku',l.sku,'ordered',l.quantity,'shipped',coalesce((select sum(sl.quantity)from public.shipment_lines sl join public.shipments s on s.id=sl.shipment_id where sl.order_line_id=l.id and s.status='dispatched'),0),'remaining',greatest(0,l.quantity-coalesce((select sum(sl.quantity)from public.shipment_lines sl join public.shipments s on s.id=sl.shipment_id where sl.order_line_id=l.id and s.status='dispatched'),0)))order by l.id),'[]')from public.order_lines l where l.order_id=o.id));end $$;

revoke all on function public.admin_create_pick_list(uuid,uuid,text),public.admin_confirm_pick_line(uuid,uuid,numeric,text),public.admin_create_shipment(uuid,text),public.admin_assign_shipment_allocation(uuid,uuid,text),public.admin_create_shipment_package(uuid,numeric,text,text),public.admin_set_package_content(uuid,uuid,numeric,text),public.admin_verify_shipment(uuid,text,numeric,text,text),public.admin_lock_shipment(uuid,text),public.admin_dispatch_shipment(uuid,text),public.admin_cancel_planned_shipment(uuid,text),public.get_order_fulfillment_summary(uuid) from public,anon;grant execute on function public.admin_create_pick_list(uuid,uuid,text),public.admin_confirm_pick_line(uuid,uuid,numeric,text),public.admin_create_shipment(uuid,text),public.admin_assign_shipment_allocation(uuid,uuid,text),public.admin_create_shipment_package(uuid,numeric,text,text),public.admin_set_package_content(uuid,uuid,numeric,text),public.admin_verify_shipment(uuid,text,numeric,text,text),public.admin_lock_shipment(uuid,text),public.admin_dispatch_shipment(uuid,text),public.admin_cancel_planned_shipment(uuid,text),public.get_order_fulfillment_summary(uuid) to authenticated;
commit;
