import { notFound } from "next/navigation";
import { CatalogForm, type CatalogField } from "@/components/catalog/catalog-form";
import { PageHeading } from "@/components/ui/page-heading";
import { can, requirePermission } from "@/lib/auth/authorization";
import { saveCategory,saveProduct,saveSupplier,saveSupplierProduct,saveVariant } from "@/lib/catalog/actions";
import { createClient } from "@/lib/supabase/server";

const status:CatalogField={name:"status",label:"Status",options:[{value:"active",label:"Active"},{value:"inactive",label:"Inactive"}]};
export default async function Page({params}:{params:Promise<{kind:string;id:string}>}){
 const{kind,id}=await params;if(!/^[0-9a-f-]{36}$/i.test(id))notFound();const supabase=await createClient();
 if(kind==="category"){await requirePermission("categories.manage");const{data}=await supabase.from("product_categories").select("*").eq("id",id).maybeSingle();if(!data)notFound();return <Editor title="Edit Product Category" action={saveCategory} values={{id,name:data.name,slug:data.slug,description:data.description,status:data.status,displayOrder:data.display_order}} fields={[{name:"name",label:"Name",required:true},{name:"slug",label:"Slug",required:true},{name:"description",label:"Description"},{name:"displayOrder",label:"Display order",type:"number",required:true},status]}/>}
 if(kind==="product"){await requirePermission("products.manage");const[{data},{data:cats}]=await Promise.all([supabase.from("products").select("*").eq("id",id).maybeSingle(),supabase.from("product_categories").select("id,name").order("display_order")]);if(!data)notFound();return <Editor title="Edit Product" action={saveProduct} values={{id,categoryId:data.category_id,name:data.product_name,description:data.description,type:data.product_type,status:data.status,uom:data.default_unit_of_measure,lot:data.lot_tracking_required,expiration:data.expiration_tracking_required,coa:data.coa_tracking_applicable,backorder:data.future_backorder_eligible,notes:data.internal_notes}} fields={[{name:"categoryId",label:"Category",required:true,options:(cats??[]).map(x=>({value:x.id,label:x.name}))},{name:"name",label:"Product name",required:true},{name:"type",label:"Product type",required:true},{name:"uom",label:"Default unit",required:true},{name:"status",label:"Status",options:[{value:"active",label:"Active"},{value:"inactive",label:"Inactive"},{value:"depleted",label:"Depleted"},{value:"discontinued",label:"Discontinued"}]},{name:"description",label:"Description"},{name:"notes",label:"Internal notes"},{name:"lot",label:"Lot tracking",type:"checkbox"},{name:"expiration",label:"Expiration/BUD tracking",type:"checkbox"},{name:"coa",label:"COA applicable",type:"checkbox"},{name:"backorder",label:"Future backorder eligibility",type:"checkbox"}]}/>}
 if(kind==="variant"){await requirePermission("products.manage");const[{data},{data:products}]=await Promise.all([supabase.from("product_variants").select("*").eq("id",id).maybeSingle(),supabase.from("products").select("id,product_name").order("product_name")]);if(!data)notFound();return <Editor title="Edit Product Variant" action={saveVariant} values={{id,productId:data.product_id,sku:data.sku,name:data.variant_name,strength:data.strength_value,strengthUnit:data.strength_unit,packageSize:data.package_size,packageUnit:data.package_unit,concentration:data.concentration,volume:data.volume_value,volumeUnit:data.volume_unit,barcode:data.barcode,status:data.status}} fields={[{name:"productId",label:"Product",required:true,options:(products??[]).map(x=>({value:x.id,label:x.product_name}))},{name:"sku",label:"SKU",required:true},{name:"name",label:"Variant name",required:true},{name:"strength",label:"Strength",type:"number"},{name:"strengthUnit",label:"Strength unit"},{name:"packageSize",label:"Package size",type:"number"},{name:"packageUnit",label:"Package unit"},{name:"concentration",label:"Concentration"},{name:"volume",label:"Volume",type:"number"},{name:"volumeUnit",label:"Volume unit"},{name:"barcode",label:"Barcode"},status]}/>}
 if(kind==="supplier"){await requirePermission("suppliers.manage");const{data}=await supabase.from("suppliers").select("*").eq("id",id).maybeSingle();if(!data)notFound();return <Editor title="Edit Supplier" action={saveSupplier} values={{id,name:data.supplier_name,code:data.supplier_code,contact:data.contact_name,email:data.email,phone:data.phone,website:data.website,country:data.country,address1:data.address_line_1,address2:data.address_line_2,city:data.city,region:data.region,postal:data.postal_code,status:data.status,lead:data.lead_time_days,notes:data.internal_notes}} fields={[{name:"name",label:"Supplier name",required:true},{name:"code",label:"Supplier code",required:true},{name:"contact",label:"Contact name"},{name:"email",label:"Email",type:"email"},{name:"phone",label:"Phone"},{name:"website",label:"Website",type:"url"},{name:"country",label:"Country"},{name:"address1",label:"Address line 1"},{name:"address2",label:"Address line 2"},{name:"city",label:"City"},{name:"region",label:"State / region"},{name:"postal",label:"Postal code"},{name:"lead",label:"Lead time days",type:"number"},{name:"notes",label:"Internal notes"},status]}/>}
 if(kind==="supplier-product"){const context=await requirePermission("suppliers.manage");const[{data},{data:suppliers},{data:variants}]=await Promise.all([supabase.from("supplier_product_variants").select("*").eq("id",id).maybeSingle(),supabase.from("suppliers").select("id,supplier_name").eq("status","active"),supabase.from("product_variants").select("id,sku,variant_name").eq("status","active")]);if(!data)notFound();const fields:CatalogField[]=[{name:"supplierId",label:"Supplier",required:true,options:(suppliers??[]).map(x=>({value:x.id,label:x.supplier_name}))},{name:"variantId",label:"Variant",required:true,options:(variants??[]).map(x=>({value:x.id,label:`${x.sku} — ${x.variant_name}`}))},{name:"supplierSku",label:"Supplier SKU"},{name:"lead",label:"Typical lead days",type:"number"},{name:"moq",label:"Minimum order quantity",type:"number"},{name:"preferred",label:"Preferred supplier",type:"checkbox"},status];const values:Record<string,string|number|boolean|null>={id,supplierId:data.supplier_id,variantId:data.product_variant_id,supplierSku:data.supplier_sku,lead:data.typical_lead_time_days,moq:data.minimum_order_quantity,preferred:data.is_preferred,status:data.status};if(can(context,"supplier_costs.manage")){fields.push({name:"cost",label:"Supplier cost",type:"number"},{name:"currency",label:"Currency",required:true});const{data:cost}=await supabase.from("supplier_product_variant_costs").select("supplier_cost,currency").eq("relationship_id",id).maybeSingle();values.cost=cost?.supplier_cost??null;values.currency=cost?.currency??"USD";}return <Editor title="Edit Supplier / Product Relationship" action={saveSupplierProduct} values={values} fields={fields}/>}
 notFound();
}
function Editor({title,action,fields,values}:{title:string;action:(state:{error?:string;success?:string},form:FormData)=>Promise<{error?:string;success?:string}>;fields:CatalogField[];values:Record<string,string|number|boolean|null|undefined>}){return <><PageHeading title={title} description="Existing values are loaded through tenant-isolated server queries."/><div className="mt-8"><CatalogForm title={title} action={action} fields={fields} values={values}/></div></>}
