"use server";
import{revalidatePath}from"next/cache";import{getAppContext}from"@/lib/auth/authorization";import{createClient}from"@/lib/supabase/server";
export type ProcurementActionState={error?:string;success?:string};
export async function resolveInventoryHold(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("qc.release","admin_resolve_inventory_hold",{target_quarantine_transaction_id:numberValue(f,"transactionId"),target_approved:numberValue(f,"approved"),target_rejected:numberValue(f,"rejected"),target_reason:str(f,"reason",1000,true),target_idempotency_key:str(f,"requestKey",120,true)},["/qc","/inventory"]));}
export async function processInventoryExpiration(){return wrap(()=>mutate("qc.release","admin_process_inventory_expiration",{},["/qc","/inventory"]));}
const str=(f:FormData,n:string,max=1000,required=false)=>{const v=String(f.get(n)??"").trim();if((required&&!v)||v.length>max)throw new Error(`Invalid ${n}.`);return v};
const id=(f:FormData,n:string,optional=false)=>{const v=str(f,n,36,!optional);if(optional&&!v)return null;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v))throw new Error(`Invalid ${n}.`);return v};
const numberValue=(f:FormData,n:string,optional=false)=>{const v=str(f,n);if(optional&&!v)return null;const x=Number(v);if(!v||!Number.isFinite(x))throw new Error(`Invalid ${n}.`);return x};
const date=(f:FormData,n:string)=>{const v=str(f,n,30);if(!v)return null;if(!/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2}(\.\d{1,3})?)?(Z|[+-]\d{2}:\d{2})?)?$/.test(v)||Number.isNaN(Date.parse(v)))throw new Error(`Invalid ${n}.`);return v};
async function mutate(permission:string,fn:string,args:Record<string,unknown>,paths:string[]){const c=await getAppContext();if(!c.membership?.permissions.includes(permission))throw new Error("Not authorized.");const s=await createClient(),{error}=await s.rpc(fn as never,{target_organization_id:c.membership.organizationId,...args}as never);if(error)return{error:error.code==="23505"?"A record with that number or request key already exists.":error.message};for(const p of paths)revalidatePath(p);revalidatePath("/administration/audit-log");return{success:"Operation completed."}}
const wrap=(work:()=>Promise<ProcurementActionState>)=>work().catch(e=>({error:e instanceof Error?e.message:"Operation failed."}));
export async function savePurchaseOrder(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("purchasing.manage","admin_save_purchase_order",{target_id:id(f,"id",true),target_supplier_id:id(f,"supplierId"),target_number:str(f,"number",80,true),target_supplier_reference:str(f,"supplierReference",120),target_order_date:date(f,"orderDate"),target_expected_ship:date(f,"expectedShip"),target_expected_delivery:date(f,"expectedDelivery"),target_currency:str(f,"currency",3,true).toUpperCase(),target_subtotal:numberValue(f,"subtotal",true),target_freight:numberValue(f,"freight",true),target_additional:numberValue(f,"additional",true),target_status:str(f,"status",30,true),target_notes:str(f,"notes",5000),target_idempotency_key:str(f,"requestKey",120)||null},["/purchasing"]));}
export async function savePurchaseOrderLine(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("purchasing.manage","admin_save_purchase_order_line",{target_id:id(f,"id",true),target_purchase_order_id:id(f,"purchaseOrderId"),target_supplier_product_variant_id:id(f,"supplierProductVariantId"),target_quantity:numberValue(f,"quantity"),target_unit_cost:numberValue(f,"unitCost"),target_currency:str(f,"currency",3,true).toUpperCase(),target_expected_lot:str(f,"expectedLot",120),target_expected_expiration:date(f,"expectedExpiration"),target_expected_bud:date(f,"expectedBud"),target_expected_delivery:date(f,"expectedDelivery"),target_notes:str(f,"notes",5000)},["/purchasing"]));}
export async function saveInboundShipment(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("purchasing.manage","admin_save_inbound_shipment",{target_id:id(f,"id",true),target_supplier_id:id(f,"supplierId"),target_purchase_order_id:id(f,"purchaseOrderId",true),target_reference:str(f,"reference",120,true),target_carrier:str(f,"carrier",120),target_tracking:str(f,"tracking",160),target_expected:date(f,"expected"),target_actual:date(f,"actual"),target_status:str(f,"status",40,true),target_packages:numberValue(f,"packages",true),target_warehouse_id:id(f,"warehouseId"),target_notes:str(f,"notes",5000)},["/inbound-shipments"]));}
export async function receivePurchaseOrder(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("receiving.manage","admin_receive_purchase_order",{target_purchase_order_line_id:id(f,"purchaseOrderLineId"),target_inbound_shipment_id:id(f,"inboundShipmentId",true),target_warehouse_id:id(f,"warehouseId"),target_location_id:id(f,"locationId"),target_lot_number:str(f,"lotNumber",120,true),target_expiration:date(f,"expiration"),target_bud:date(f,"bud"),target_quantity:numberValue(f,"quantity"),target_accepted:numberValue(f,"accepted"),target_damaged:numberValue(f,"damaged"),target_rejected:numberValue(f,"rejected"),target_qc_required:true,target_reference:str(f,"reference",120,true),target_reason:str(f,"reason",1000),target_idempotency_key:str(f,"requestKey",120,true)},["/receiving","/inventory","/qc"]));}
export async function recordQcInspection(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("qc.inspect","admin_record_qc_inspection",{target_receiving_line_id:id(f,"receivingLineId"),target_lot_id:id(f,"lotId"),target_warehouse_id:id(f,"warehouseId"),target_location_id:id(f,"locationId"),target_status:str(f,"status",30,true),target_inspected:numberValue(f,"inspected"),target_approved:numberValue(f,"approved"),target_quarantined:numberValue(f,"quarantined"),target_rejected:numberValue(f,"rejected"),target_reason_code:str(f,"reasonCode",120),target_notes:str(f,"notes",5000),target_idempotency_key:str(f,"requestKey",120,true)},["/qc","/inventory"]));}
export async function releaseQcInventory(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("qc.release","admin_release_qc_inventory",{target_qc_inspection_id:id(f,"inspectionId"),target_warehouse_id:id(f,"warehouseId"),target_location_id:id(f,"locationId"),target_quantity:numberValue(f,"quantity"),target_idempotency_key:str(f,"requestKey",120,true)},["/qc","/inventory"]));}
export async function saveQualityDocument(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("quality_documents.manage","admin_save_quality_document",{target_id:id(f,"id",true),target_lot_id:id(f,"lotId"),target_type:str(f,"type",40,true),target_name:str(f,"name",200,true),target_laboratory:str(f,"laboratory",200),target_report:str(f,"report",160),target_test_date:date(f,"testDate"),target_status:str(f,"status",30,true),target_notes:str(f,"notes",5000),target_storage_reference:str(f,"storageReference",500)},["/quality-documents"]));}
export async function saveSupplierIssue(_:ProcurementActionState,f:FormData){return wrap(()=>mutate("supplier_issues.manage","admin_save_supplier_issue",{target_id:id(f,"id",true),target_supplier_id:id(f,"supplierId"),target_purchase_order_id:id(f,"purchaseOrderId",true),target_receiving_id:id(f,"receivingId",true),target_inbound_shipment_id:id(f,"inboundShipmentId",true),target_lot_id:id(f,"lotId",true),target_issue_type:str(f,"issueType",40,true),target_quantity:numberValue(f,"quantity",true),target_severity:str(f,"severity",20,true),target_description:str(f,"description",5000,true),target_status:str(f,"status",40,true),target_supplier_notified:date(f,"supplierNotified"),target_owner:id(f,"owner",true),target_resolution:str(f,"resolution",5000),target_resolution_type:str(f,"resolutionType",40)||null,target_replacement_quantity:numberValue(f,"replacementQuantity",true),target_replacement_expected:date(f,"replacementExpected"),target_credit_amount:numberValue(f,"creditAmount",true),target_currency:str(f,"currency",3)||null,target_idempotency_key:str(f,"requestKey",120)||null},["/supplier-issues"]));}
